### ISSUE TITLE
automated testing ?

### ISSUE THREAD

**Issue by iynere** [circleci/circleci-images#106]
can we work on some kind of automated testing process for this repo ?

some ideas:

- add a CCI job to just run `make` for all branches, even if only some branches actually trigger pushes to Docker Hub
- or use a third Docker Hub account (in addition to circleci, notnoopci) to host `test` images, make all those images private so customers don't use them by mistake

other thoughts ?

**Comment by eric-hu** [comment]
+100

Right now, most branches only build Dockerfiles from what I can tell.  We'd have to add a job to build an image.  There is a `build and publish` job that we can refer to.  I think it would be a big improvement to just build an image before it goes to a publishing branch.  That could be the first test we implement.

**Comment by iynere** [comment]
we did this :)
