### ISSUE TITLE
Old version of Git in CircleCI 2

### ISSUE THREAD

**Issue by ryansmith94** [circleci/circleci-images#128]
Hey I've found that the pre-built images for CircleCI 2 are using an old version of Git (specifically 2.1.4). Could that please be updated? I'd make a PR, but having looked around the code here I'm not 100% sure where to make that change.

This was discovered in https://github.com/semantic-release/semantic-release/issues/559 and the build that shows the issue is https://circleci.com/gh/HT2-Labs/semantic-release/11 (shows that it's using `circleci/node:8` and the "Semantic Release Debugging" step shows that it's using git v2.1.4).

**Comment by iynere** [comment]
hi ryan, we're currently using the version of git that is available in the underlying OS official repositories that our convenience images are based on—these (especially Debian) are known to not have the latest bleeding-edge versions of some packages (like git).

if you'd like a newer version of git, it's easy to customize the particular image you're using—probably only takes one or two lines, something like:

```
FROM circleci/node:8
RUN [code to install the particular version of git that you'd like to use]
```

**Comment by ryansmith94** [comment]
Ok thanks.

**Comment by iynere** [comment]
happy to help! @wchargin just checking internally first to see if there's a reason all those links are to debian/stretch packages... or if it's just a mistake

**Comment by iynere** [comment]
& based on the above @ryansmith94, if you use a `-stretch`-tagged CircleCI image, you will get a newer version of git

**Comment by ryansmith94** [comment]
Thanks @iynere 👍

**Comment by iynere** [comment]
see https://github.com/circleci/circleci-docs/pull/2826 @ryansmith94 @wchargin
