### ISSUE TITLE
Oracle JDK image

### ISSUE THREAD

**Issue by Hronom** [circleci/circleci-images#134]
Please add image with `oraclejdk`. 
You can use this PPA for easy creation of image: https://launchpad.net/~webupd8team/+archive/ubuntu/java
Here is more description: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

Now Oracle java only usable via machines.

Thanks in advance.

**Comment by ryanwohara** [comment]
We simply extend community images and oraclejdk is not an image:
https://hub.docker.com/_/oraclejdk/

Feel free to build your own, though.

**Comment by Hronom** [comment]
Hey the link that you drop not works.
I mean that can you please add image with Oracle JDK. The `oraclejdk` is suggested name.

Now JDK from Oracle only usable via machines.

**Comment by ryanwohara** [comment]
I am reopening this issue for us to write a readme explaining why there is no oraclejdk.

**Comment by levlaz** [comment]
> Hey the link that you drop not works.

Hey, sorry for the confusion. Thats the point here. There is no official oraclejdk image. Due to licensing restrictions we are not able to distribute it.

If you need oraclejdk you will need to make your own image.
