### ISSUE TITLE
fastlane in android

### ISSUE THREAD

**Issue by iynere** [circleci/circleci-images#135]
i'm thinking it'd be good to add fastlane to our android images—thoughts ?

**Comment by gengjiawen** [comment]
I don't think it going to be useful, since this is not widely adopter in android community.

**Comment by felicianotech** [comment]
GitHub doesn't support polls but perhaps a poll on Twitter or Discuss?

**Comment by gengjiawen** [comment]
I still think we need to make image the simple, introduce some tools not widely adopted.

**Comment by marcomorain** [comment]
The best way to accomplish this is to put a `Gemfile` into your project that declares your dependency on `fastlane`, and then run `bundle install` and `bundle exec fastlane` in your build. You will want to cache your Ruby dependencies like this: https://circleci.com/docs/2.0/language-ruby/
