### ISSUE TITLE
Re-enable Xdebug on PHP 7.2

### ISSUE THREAD

**Issue by jaydiablo** [circleci/circleci-images#148]
I was testing with PHP 7.2 and noticed that coverage didn't run because xdebug wasn't installed.

I noticed this line in the build images script: https://github.com/circleci/circleci-images/blob/711855ef90f3d566ffce10c48c3f4c5bb4c98703/php/generate-images#L17

That was added in this PR: https://github.com/circleci/circleci-images/pull/114 (specifically this commit: https://github.com/circleci/circleci-images/pull/114/commits/d9d7c5a9d65a45280eb9e8c84520c539b5c41340).

Xdebug does work on PHP 7.2, looks like it just came out of Beta on the 29th of January (https://xdebug.org/download.php).

Possible to get it re-enabled in php 7.2 images?

Thanks!

**Comment by ryanwohara** [comment]
Sure thing!

**Comment by jaydiablo** [comment]
Thanks!
