### ISSUE TITLE
Do we need xvfb in basic images?

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#151]
So `xvfb` is installed in our Basic images but most of the tools you'd need to make it useful are in the `browsers` variant. Should we move it to that variant? Is there a reason it should stay in the basic image?

Blocked by #153.

**Comment by eric-hu** [comment]
It may not be necessary, but it's worth considering how this might affect backwards compatibility if we remove it now.  Since we rewrite tags, this could cause users to have failed jobs.

**Comment by felicianotech** [comment]
Good point. We should first figure out how to not rewrite tags.

**Comment by zzak** [comment]
Chrome headless negates the need for xvfb, so hoping more people switch to that and stop using it.

**Comment by ryanwohara** [comment]
Having it installed is fine. We only have it running in the browsers image.

I agree with zzak we might be able to remove it the end of the year with people moving to headless Chrome support.

**Comment by felicianotech** [comment]
That sounds like the consensus to me.
