### ISSUE TITLE
Update android image ruby version

### ISSUE THREAD

**Issue by Laimiux** [circleci/circleci-images#152]
Currently, the version is 2.4.1 while the latest stable is 2.4.3

**Comment by felicianotech** [comment]
The latest in the 2.4 series. v2.5.0 is the latest release. Would you have a preference of one vs the other? Why?

**Comment by Laimiux** [comment]
I'm okay with going with v2.5.0 release as well. Our build files are actually written in v2.3.6 so if I'm updating, it would be nice to jump to latest. Maybe having a couple of stable ruby versions preinstalled would be better so it's possible to select?

**Comment by zzak** [comment]
We should only need to update these lines to upgrade the Ruby version for android images:
https://github.com/circleci/circleci-images/blob/master/android/Dockerfile.m4#L52-L55

**Comment by felicianotech** [comment]
Due to #153, I think a smaller increment makes more sense so I'll open a PR for Ruby v2.4.3.
