### ISSUE TITLE
PHP5 images no longer have xdebug support

### ISSUE THREAD

**Issue by far-blue** [circleci/circleci-images#155]
A recent PR (#150) broke xdebug support for the php56 images. Rather than just not installing xdebug which then breaks code coverage for unit testing, may I suggest the version of xdebug simply be locked to v2.5.5 using `pecl install xdebug-2.5.5`.

I guess the alternative is that every php56 user either creates a custom image or runs the `pecl install` step on every build. I suspect most people will just do the latter which is extra load on the build system and wasteful.

**Comment by ryanwohara** [comment]
https://github.com/circleci/circleci-images/pull/156

**Comment by far-blue** [comment]
thankyou :)
