### ISSUE TITLE
javafx in openjdk image

### ISSUE THREAD

**Issue by jgkamat** [circleci/circleci-images#171]
Hi,

I recently tried to migrate a 1.0 javafx app which built automaticaly on the old 1.0 infrastructure. This became a bit harder than I expected because javafx isn't available in the openjdk image. Could it be added please? This is available in the `openjfx` package on debian.

**Comment by ryanwohara** [comment]
New images are being built right now with `openjfx` in this job:
https://circleci.com/gh/circleci/circleci-images/5527
