### ISSUE TITLE
Ruby 2.5.1 image, please?

### ISSUE THREAD

**Issue by skatkov** [circleci/circleci-images#180]
Ruby has released a security patch, it would be really great if it would be available on 

https://hub.docker.com/r/circleci/ruby/tags/

Any chance we can speed this up a bit? (i'm a bit nervous about security, sorry)

**Comment by renchap** [comment]
Ruby 2.4.4, 2.3.7 and 2.2.10 has also been released with the same security fixes.

**Comment by capripot** [comment]
#need

**Comment by skatkov** [comment]
Thanks to @felicianotech for a fix. This is a second time I've raised issue of images updated, first with support and now here. Really happy that this is finally is resolved once and for all.
