### ISSUE TITLE
Generate images for Node 8.11.1

### ISSUE THREAD

**Issue by rodrigok** [circleci/circleci-images#183]
Node 8.11.1 has some importante fixes https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2018-03-29-version-8111-carbon-lts-mylesborins

Can you generate the images using the latest versions?

**Comment by felicianotech** [comment]
On its way.

**Comment by rodrigok** [comment]
Related to https://github.com/RocketChat/Rocket.Chat/pull/10314

**Comment by felicianotech** [comment]
Done

**Comment by rodrigok** [comment]
@felicianotech Thanks
