### ISSUE TITLE
NodeJS 8.9 images

### ISSUE THREAD

**Issue by rodrigok** [circleci/circleci-images#186]
Any chance to have the node 8.9 images available?

The 8.10 and 8.11 versions have a seg fault issue as you can check here https://github.com/nodejs/node/issues/19274, it was already solved but the release of 8.11.2 will take some days or weeks to land.

**Comment by felicianotech** [comment]
A CircleCI Node v8.9 image is available.

Here's a test build that uses it: https://circleci.com/gh/felicianotech/cci-testing-pub/635
