### ISSUE TITLE
Build stretch variants of Ruby images

### ISSUE THREAD

**Issue by renchap** [circleci/circleci-images#187]
Debian 9 (Stretch) has been released in June 2017. The official Ruby docker images are now built both on Jessie (Debian 8) and Stretch (Debian 9).

Would it be possible to have new variants of the Ruby CircleCI images built from the Stretch official ones? This would be incredibly useful to people who need recent versions of libraries.

In my case, `ruby-vips` requires `libvips` > 8, only available on Stretch.

Thanks,

**Comment by DanToml** [comment]
@renchap Hey, we already build stretch variants of most (all?) of the ruby images (https://hub.docker.com/r/circleci/ruby/tags/) - Is there a particular image that is missing that you expect?

**Comment by renchap** [comment]
My bad, I searched for stretch in this repo, and did not check the published tags... 🙇‍♂️
`2.4.4-stretch-node-browsers` is exactly what I needed, thanks!

**Comment by DanToml** [comment]
@renchap No problem!
