### ISSUE TITLE
Node versions are incorrect

### ISSUE THREAD

**Issue by chrisbutler** [circleci/circleci-images#188]
Hi, the node version for `2.4.1-node-broswers` is `8.5.0` and for `2.5.0-node-browsers` it is `8.10.0`?!?! 

Should they not all be `8.9.4`?

**Comment by levlaz** [comment]
Hey @chrisbutler our base images are the same ones that are available in the official docker hub repo: https://hub.docker.com/r/library/node/tags/

The only tags you should see on our images are the ones that the docker node team offers as well.

**Comment by chrisbutler** [comment]
hey @levlaz, i apologize... i just realized i left out a crucial detail. these are all `ruby` images with node included

how is the bundled `node` version determined for the `ruby` images?

**Comment by felicianotech** [comment]
@chrisbutler The NodeJS version used is the latest stable version out when the image was created.
