### ISSUE TITLE
Gradle missing from android images.

### ISSUE THREAD

**Issue by dopry** [circleci/circleci-images#189]
In a build with the android:api-{{n}}-node8-alpha images gradle wrapper is not found on the path or in the SDK.

**Comment by tbroyer** [comment]
See #118

**Comment by dopry** [comment]
@tbroyer, why see #118? It was closed without resolution. How does that help anyone?

**Comment by tbroyer** [comment]
You're supposed to use the Gradle Wrapper: `./gradlew …`

**Comment by dopry** [comment]
@tbroyer how can one use the gradle wrapper if it is not there?

**Comment by tbroyer** [comment]
You're supposed to commit `gradlew`, `gradlew.bat` and the `gradle/wrapper/gradle-wrapper.{jar,properties}` files into your Git repository.
https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by niccorder** [comment]
I'd like to generate the gradle wrapper at build time... and as such I need gradle to run the `gradle wrapper` task.

👍 for adding it into the android images.

**Comment by JakeWharton** [comment]
Unless you are pushing that back to the git repo, there's no point in generating the gradle wrapper at build time using a global installation. If you are not checking in the wrapper then you would just invoke your build using the global installation. And even if you are generating the wrapper to push somewhere you would want to download the installation yourself to ensure it's of the correct version.

Count my :-1: on adding a global installation. Gradle 4.9 was just released today and it is incompatible with the stable versions of the Android Gradle plugin. If the image updated a global Gradle version and people were using it their builds they all would start failing today.

**Comment by niccorder** [comment]
@jakewharton  I'm not sure I understand.

Gradle has a wrapper task which let's you specify the wrapper version + distribution url to download it from. I like to use this so I don't have to check in binaries into SCM. I just need the global Gradle to call `gradle wrapper` then would use `./gradlew` for any actual tasks. Reference https://docs.gradle.org/current/userguide/gradle_wrapper.html#customizing_wrapper

However... I see your point that if people use the global Gradle instead of the wrapper it can cause some serious issues. Perhaps making it an opt-in would be a happy medium?

**Comment by JakeWharton** [comment]
It's pretty easy to make this an opt-in by deriving your own container image. For example, I need Node 10 in mine so I add it to the `api-28-alpha` image provided by Circle CI with a 3-line `Dockerfile` and 2 commands to build and push it:

https://github.com/JakeWharton/SdkSearch/blob/dbd792a491e200295bd3b5b60711461ec828988a/.circleci/images/primary/Dockerfile#L15-L18

**Comment by niccorder** [comment]
That's a really interesting point. The project does have to fully configure before runs.

Thanks for the follow up!

**Comment by iynere** [comment]
thanks for all your input folks! i'm going to close this issue for now, it seems like the consensus is that it's a bit of an anti-pattern to include gradle in the docker image itself.

that said, if it seems like some additional info would be helpful w.r.t @tbroyer's point here—

https://github.com/circleci/circleci-images/issues/189#issuecomment-392947733

—then i would encourage anyone to submit a PR to our [Android language guide](circleci.com/docs/2.0/language-android)

thanks again! @niccorder @JakeWharton @dopry
