### ISSUE TITLE
generate.sh: variants do not include IMAGE_CUSTOMIZATIONS

### ISSUE THREAD

**Issue by dnephin** [circleci/circleci-images#195]
For example `python` has 3 variants, none of them include `pipenv`.

**Comment by notnoopci** [comment]
Mind if you provide details with your observation?  I checked the python variants and they all contain `pipenv`:

```
$ docker run -it --rm circleci/python:3.6.5 pipenv --version
pipenv, version 11.10.4
$ docker run -it --rm circleci/python:3.6.5-node pipenv --version
pipenv, version 11.10.4
$ docker run -it --rm circleci/python:3.6.5-browsers pipenv --version
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
pipenv, version 11.10.4
```

It's worth noting that `generate.sh` only includes `IMAGE_CUSTOMIZATIONS` in the original base image, as variants images inherit from that image.  `circleci/python:3.6.5` is a parent of `circleci/python:3.6.5-node`, as can be seen in https://6594-85091879-gh.circle-artifacts.com/0/circleci-bundles/python/images/3.6.5/node/Dockerfile .

**Comment by dnephin** [comment]
Ah, I missed that the variants use a different base. I'll close this.
