### ISSUE TITLE
Add make to OpenJDK images

### ISSUE THREAD

**Issue by fiskeben** [circleci/circleci-images#205]
I'm missing the `make` tool in the OpenJDK images. Would it be possible to install `build-essential` there?

`make` is available in the Node.js and Golang images, as far as I can tell (and possibly more) but I suppose that's more by coincidence because it's available in the base image?

I know I can just install it myself as part of my build or make my own build image, but in my opinion that is counter to the idea about having a build image. An image for building software should supply the proper tools.

**Comment by ryanwohara** [comment]
What version are you seeing this in?

**Comment by iynere** [comment]
@fiskeben as far as we can tell, all our openjdk images pull from the `jdk`-tagged images on https://hub.docker.com/_/openjdk, which all pull from `buildpack-deps`, which _should_ have `make` installed already...... unless you're perhaps using a very old openjdk image ?

**Comment by iynere** [comment]
that said, i also explicitly added build-essential in the changes that were just merged into master, so this should be (extra) good now !
