### ISSUE TITLE
Make option to build but not publish images

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#209]
Right now for local dev, I'd run `make -j <an-image>/publish_images` in order to build images and see if they actually build. Those images are also pushed to Docker Hub, which fails for me and for any customer who would want to work on this repo.

I'd like to add a way to build but not publish images. I think the easiest way would be to add a CLI flag to the publish script to set a `BUILD_ONLY` boolean. The script checks that before trying to `docker push`.

Anyone think this will be useful?

**Comment by iynere** [comment]
@felicianotech are you thinking of the option of building them locally ? or you'd like them to build first, then publish separately, as part of our regular flow ?

**Comment by iynere** [comment]
@felicianotech building these images locally would destroy your hard drive, altho i guess if you were just trying out a couple it wouldn't be so bad

**Comment by felicianotech** [comment]
Build locally and that's it. While I'm working on this repo, to fix something for example, I build the images locally in order to make sure they work. The script fails on `docker push` which is irrelevant for me because I don't need to push. I want to avoid those errors.

**Comment by felicianotech** [comment]
And yes, my SSD has over 100GB worth of Docker images at this point.

**Comment by iynere** [comment]
@felicianotech once you run `make -j` can't you just build the images manually, since you have all the dockerfiles ? or do you want to have a programmatic way to build them all ?

**Comment by felicianotech** [comment]
I want it scripted because there can easily be 30+ images to build.

**Comment by iynere** [comment]
IMO, it would be nice to have a way to build an entire bundle / repo / of images at once, sort of a `make -j <an-image>/build` that would build all the variants for a particular repo locally, since it's usually 1 or the other repo that breaks at a time.... that said, when they _do_ break, building all the variants as opposed to just building one of them probably doesn't tell you anything new

**Comment by felicianotech** [comment]
That's what I'm suggesting. Accept that the publish script already does this but with `docker push`. If you think this is useful, I can add the option to the script and Makefile today. Just wanted to make sure someone agrees with me this can be useful.

**Comment by iynere** [comment]
yeah go for it !! 🙏

**Comment by felicianotech** [comment]
This repo is mostly in maintenance mode so closing. The new image system doesn't use make and can generate Dockerfiles locally just fine.
