### ISSUE TITLE
Older Software Releases Are Missing Their Images (Go 1.90, MariaDB 10.2.12 for example)

### ISSUE THREAD

**Issue by joshdk** [circleci/circleci-images#214]
Started hitting some build failures at ~4:50 PM Friday, June 15, 2018 (PDT).

#### Steps to reproduce:

Attempt to pull the image from public Docker Hub:

```
$ docker pull circleci/golang:1.10.2
Error response from daemon: manifest for circleci/golang:1.10.2 not found
```

Or, as a CircleCI build stage

```
Build-agent version 0.0.6347-92eac3d (2018-06-13T18:13:12+0000)
Starting container circleci/golang:1.10.2
  image cache not found on this host, downloading circleci/golang:1.10.2
Error response from daemon: manifest for circleci/golang:1.10.2 not found
```

Hope that this helps debug, and (possibly restore) the image disappearance. Cheers!

**Comment by oshalygin** [comment]
getting this as well for 1.9.2.  Any workaround?  Should we specify a non-circle image in the pipeline?

**Comment by felicianotech** [comment]
There seems to have been an issue with our build process on Docker Hub that has caused images for older releases (of Go for example) to be removed.

We're looking into this.

A **temporarily solution** is to use a newer release. For example, For Go v1.9.2 or Go v1.10.2, use `:1.9.7` or `:1.10.3` respectively. Also, using the less specific tags of `:1.9` and `:1.10` will work as well.

**Comment by oshalygin** [comment]
@felicianotech is there any downside to just using the `go` docker image instead?

eg: `go:1.10`

**Comment by iynere** [comment]
hi there, starting to get these back up on Docker Hub, thanks for your patience! @oshalygin @mujtaba-ahmad @joshdk https://hub.docker.com/r/circleci/golang/tags

**Comment by iynere** [comment]
@joshdk mariadb images should be back shortly https://hub.docker.com/r/circleci/mariadb/tags

**Comment by oshalygin** [comment]
Thanks @iynere !

**Comment by HanmeiTang** [comment]
Hi everyone, I hope this is the right place to report this issue. We got the same problem from the missing `circleci/mongo:3.5.6` image from today. The following is the error message:

```
Starting container circleci/mongo:3.5.6
  image cache not found on this host, downloading circleci/mongo:3.5.6
Error response from daemon: manifest for circleci/mongo:3.5.6 not found
```

Thanks!

**Comment by iynere** [comment]
hi there @HanmeiTang, can you try `circleci/mongo:3.5`, `3.5.3`, `3.5.4`, `3.5.9`, `3.5.10`, or `3.5.13` ? 🙏

**Comment by iynere** [comment]
closing this issue, because almost everything should be back. if there are still some specific older sub-versions that seem to  be missing, we must have built them a long time ago, before our current image-building workflow was put in place... there should be a wide range of alternatives, but if anyone for some technical reason needs to be pinned to a hyper-specific sub-release of a particular image that we still seem to be missing, feel free to reopen & i can try to address it on a case-by-case basis 🙏

**Comment by HanmeiTang** [comment]
@iynere Thanks for the information! I tried `circleci/mongo:3.5`, `3.5.3` and `3.5.6`, but received the same error message.

**Comment by iynere** [comment]
oh, huh, that's weird. those should be there, i'll look into it. these ones _definitely_ exist:

```
3.5.10
3.5.10-ram
3.5.13
3.5.13-jessie
3.5.13-jessie-ram
3.5.13-ram
```

**Comment by iynere** [comment]
you can verify for yourself like this : 

`curl "https://registry.hub.docker.com/v1/repositories/circleci/mongo/tags" | jq -r '.[].name'`

@HanmeiTang
