### ISSUE TITLE
Pull in Elixir 1.6.6 and OTP 21

### ISSUE THREAD

**Issue by davydog187** [circleci/circleci-images#219]
Its not obvious to me by looking at the generate scripts how versions get pulled in, but Elixir 1.6.6 and OTP 21 were released earlier this week, and I would like to start using them in my builds. Happy to put in a PR if thats necessary, but would love to push along.

Thanks!

**Comment by felicianotech** [comment]
Hey @davydog187, [this blog post](https://circleci.com/blog/official-image-maintenance/#docker-convenience-images) explains how our Docker Convenience Images work.

Basically, we'll have a version 24-48 hours after the [official Docker Library](https://hub.docker.com/_/elixir/) has the version. They have an open PR already: https://github.com/c0b/docker-elixir/pull/66

**Comment by davydog187** [comment]
Thanks for the info @felicianotech !
