### ISSUE TITLE
[Ruby] Node variants don't appear to be at the latest LTS release

### ISSUE THREAD

**Issue by jblock** [circleci/circleci-images#220]
Hey there! In the process of getting an automated PR for one of our dependencies in a Rails app (namely, ESLint 5.0.0) and our builds for that are failing because the `circleci/2.4.2-node-*` images are installing an older version of node:

```
7786 ◯ : docker run -it  circleci/ruby:2.4.2-node
$ node -v
v8.9.3
```

...when the current LTS Carbon release cycle is a little further:

```
         v8.9.0   (LTS: Carbon)
         v8.9.1   (LTS: Carbon)
         v8.9.2   (LTS: Carbon)
         v8.9.3   (LTS: Carbon)
         v8.9.4   (LTS: Carbon)
        v8.10.0   (LTS: Carbon)
        v8.11.0   (LTS: Carbon)
        v8.11.1   (LTS: Carbon)
        v8.11.2   (LTS: Carbon)
        v8.11.3   (Latest LTS: Carbon)
```

...and ESLint [ultimately wants a version that's at least 8.10.0](https://github.com/eslint/eslint/blob/master/package.json#L126)

I'm having some trouble parsing out whether it was intentionally pinned to that minor version or if the containers simply need to be refreshed on CircleCI's side ([I found this issue](https://github.com/circleci/circleci-images/pull/97), but it's unclear to me as to whether this still applies). Is that the case? If so, is there a way to for the container specification to specify a different version of Node, or are we (the royal we, AKA the community at large) waiting for any particular bugfixes to land before upgrading?

Also, please excuse any improper terminology for how these containers work! I'm a bit of a newbie to the docker world, so I'm still somewhat dipping my toes in with this stuff.

**Comment by ryanwohara** [comment]
The 2.4.2 image is old - use the 2.4.4 image. 
https://hub.docker.com/r/circleci/ruby/tags/
