### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by chingc** [circleci/circleci-images#221]
Python 3.7 was officially released last week. Eagerly awaiting Circle CI to have an image ready.  :)

**Comment by ryanwohara** [comment]
3.7-rc-stretch published 19 hours ago

That's the latest available from upstream at this time: https://hub.docker.com/r/library/python/tags/

**Comment by felicianotech** [comment]
@chingc The base for our Docker images comes from the upstream Docker Library images. They have an open PR for Python 3.7 but haven't merged it yet: https://github.com/docker-library/python/pull/297

**Comment by chingc** [comment]
Thanks for the info.
