### ISSUE TITLE
Incorrect Android NDK home environment variable

### ISSUE THREAD

**Issue by guillaume-tgl** [circleci/circleci-images#234]
When using the new Android images with NDK, I have an error stating: 
```
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /usr/local/opt/android-sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.
```
I was able to fix this by overriding the variable `ANDROID_NDK_HOME` to /opt/android/ndk/android-ndk-r17b/ instead of /opt/android/ndk/

**Comment by iynere** [comment]
@guillaume-tgl thanks for letting us know ! looks like someone has submitted a PR to fix this:

https://github.com/circleci/circleci-images/pull/236

we'll get this taken care of today

**Comment by guillaume-tgl** [comment]
That was fast! Thanks!

**Comment by iynere** [comment]
this should be resolved once this workflow finishes ! https://circleci.com/workflow-run/cefa061e-92eb-40de-ba1b-f18f93e83c1e see #241
