### ISSUE TITLE
Unable to start an android emulator to run the tests

### ISSUE THREAD

**Issue by shridharkalagi** [circleci/circleci-images#235]
Here is my [config.yml](https://gist.github.com/shridharkalagi/9873e121a596976b2a53e770de3b0225) file. 

[Here](https://circleci.com/gh/shridharkalagi/java-client/43 ) is the output. Tried multiple variations. Can someone help please?

**Comment by iynere** [comment]
@shridharkalagi our Android images do not support running the Android emulator:

https://circleci.com/docs/2.0/language-android/#overview

> To run emulator tests from a job, consider using an external service like Firebase Test Lab. To do this, you can use the gcloud command line. Google Cloud tools are preinstalled in our Android Docker images.

**Comment by Pantkowsky** [comment]
It's january 2020 >> any plans on supporting this anytime soon without the need for external services @iynere ?

**Comment by iynere** [comment]
@Pantkowsky hi! we are relaunching our convenience images, so we will take a fresh look at this issue. in the interim, you might try an image like this:

https://github.com/budtmo/docker-android

with the release of CircleCI Orbs, it's now much easier to use a third-party Docker image and layer on any CircleCI tooling at runtime. for example, you might try starting with the above image and then using this orb command:

https://circleci.com/orbs/registry/orb/circleci/build-tools#commands-install-ci-tools

for more info on our new images, check here:

http://github.com/circleci-public/cimg-overview

**Comment by lokst** [comment]
@Pantkowsky CircleCI now has a new Android machine image available for preview, that supports running the Android emulator: https://discuss.circleci.com/t/early-preview-new-android-machine-image/39016

**Comment by Pantkowsky** [comment]
@lokst great to know ! thank's for sharing
