### ISSUE TITLE
Role postgres is missing

### ISSUE THREAD

**Issue by olafura** [circleci/circleci-images#258]
This is what I get when the docker image spins up:
FATAL: role "postgres" does not exist

I accidentally posted this issue first to:
https://github.com/docker-library/postgres/issues/497

**Comment by iynere** [comment]
@olafura see context here : https://discuss.circleci.com/t/circleci-postgres-image-suddenly-causing-problems-role-postgres-not-found

I'll be posting our plans to address this shortly in https://discuss.circleci.com/c/announcements

**Comment by olafura** [comment]
@iynere Thanks that worked ;)
