### ISSUE TITLE
Preinstall go-junit-report in Go images

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#259]
I'm thinking of pre-installing the `go-junit-report` binary in our Go images (`circleci/golang`).

Our demo project uses it, and thus downloads it on the fly, one of my Go projects uses it, and I've noticed people also using it on CircleCI. Considering there's not many alternatives, and we want to encourage collecting test metadata, I propose we add it.

Since I'm the Go language owner, if we agree this would be useful, I'll go ahead and make the PR, update the demo app, and add it to the "Test Metadata" section of Docs as well.

**Comment by felicianotech** [comment]
@dnephin Oh hell yeah. This looks even better than `go-junit-report`.

As long as you're willing to maintain the tool for the next 1+ years (so it doesn't get killed shortly after adding it to our image) I agree, your tool would be great to add to the image.

I'm down.

Also, I haven't heard of it until now. How you mentioned it in any CircleCI blog post? If not, would you like me to?

---

As long as `gotestsum` outsides test results in the format CircleCI understands, I think we should add it.

**Comment by DanToml** [comment]
I'm a 👍 on preinstalling `gotestsum`.

**Comment by dnephin** [comment]
I definitely plan on maintaining the tool, I use it with all the projects I contribute to.

We have been using it for some internal CircleCI builds, so we've already validated that it integrates correctly.

> [Have] you mentioned it in any CircleCI blog post? If not, would you like me to?

I haven't. Talking about it in a blog post would be great, thank you!

**Comment by felicianotech** [comment]
@dnephin Post coming soon. I'll ask you for a quick review when it's ready. :)

Closing as this was fixed by @ryanwohara in #260.
