### ISSUE TITLE
Android images with Node.js v10.x?

### ISSUE THREAD

**Issue by mikemorris** [circleci/circleci-images#263]
Continuing from CircleCI-Public/example-images/issues/1

> Aside from the Node.js image itself which has tags for various versions, the Node variants for our other images carry the LTS version of Node.js. So once 10.x becomes LTS, they will have it.

I understand this, with the caveat that I would like to additionally see Node.js versions which will eventually enter LTS status added when they are initially released.

The relevant concern driving this request is that Node.js v8.x ships with npm@5 and Node.js v10.x ships with npm@6, and it's not possible to upgrade npm with `npm i -g npm` on these images.

The is particularly an issue for React Native projects, because the macos/xcode-9.4.1 and macos/xcode-10 CircleCI runtimes ship with Node.js v10.x and npm@6 (although it is possible to upgrade `npm` in that environment) and inconsistent package resolution strategies between npm versions can cause build issues.

**Comment by ryanwohara** [comment]
10.x will be LTS this month https://github.com/nodejs/Release
