### ISSUE TITLE
"sudo apt-get update" failing on default images

### ISSUE THREAD

**Issue by kevinburke** [circleci/circleci-images#269]
Running “docker run -it --rm circleci/node:10-browsers sudo apt-get update” I get the following error message:

```
Get:5 http://http.us.debian.org jessie-backports/main amd64 Packages [1172 kB]
Err http://deb.debian.org jessie/main amd64 Packages
  404  Not Found
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 3116 kB in 4s (716 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I can also reproduce by running the same command in the CircleCI environment. Please advise.

**Comment by ryanwohara** [comment]
I'm looking into it @kevinburke.

**Comment by ryanwohara** [comment]
It seems like an upstream issue with the Debian mirrors

**Comment by stevenallen05** [comment]
Having the same issue, with circleCI and without. After some digging on my own, it's an issue on some of the Debian mirrors. EG: http://cdn-fastly.deb.debian.org/debian

**Comment by ryanwohara** [comment]
I'll leave this issue open until the upstream issue gets resolved.

**Comment by ryanwohara** [comment]
This has been fully resolved.

**Comment by buitranquyet** [comment]
@ryanarlan0622 come here from https://discuss.circleci.com/t/sudo-apt-get-update-is-failing-with-default-circleci-docker-images
I can confirm that the`apt-get update` issue have been resolved. However, there is still issue with `apt-get install`. Our Circle CI builds are still failing:
<img width="1033" alt="screen shot 2018-10-23 at 08 19 42" src="https://user-images.githubusercontent.com/5118000/47328740-6acf1a80-d69c-11e8-93b0-6da82f103a04.png">

**Comment by emabishi** [comment]
i think that this has reoccurred. I get the error ```W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found` on all my Circle CI builds from the console. 
I've also SSHed into the running box and performed the command `sudo apt-get -y -qq update` and receive the same error message. I still think it's got something to do with the associated debian mirror being unavailable. 
Could you help @ryanwohara? Has anyone else triggered this?

**Comment by Nizari** [comment]
This is happening today as well.

**Comment by Akecel** [comment]
I just had this mistake, too, it seems to have reappeared, does it?  

`
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found

Fetched 9965 kB in 1s (7940 kB/s)
W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/source/Sources  404  Not Found [IP: 208.80.154.15 80]

W: Failed to fetch http://http.us.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found [IP: 208.80.154.15 80]

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code 100`

**Comment by codeflows** [comment]
FWIW I just switched from running apt within the docker image `circleci/node:10.12.0` (apparently based on jessie) to `circleci/node:10.12.0-stretch` and our problems went away.

**Comment by Akecel** [comment]
@codeflows ,

Look at this ->
https://github.com/circleci/circleci-images/issues/370#issuecomment-476580077

**Comment by Akecel** [comment]
This exit is open again here: #370
