### ISSUE TITLE
Ruby 2.3.1

### ISSUE THREAD

**Issue by owen-admedo** [circleci/circleci-images#271]
I am trying to set up a legacy app that uses ruby:2.3.1.
There is official docker images for that version, but no circleci/ruby:2.3.1.
I checked all your tags and there is circleci/ruby:2.3.3 and up.
Is it possible to have this tag added rather than us having to create a custom Docker file?

Thanks,
Owen

**Comment by felicianotech** [comment]
Hi @owen-admedo,

Apologies for the extremely late response. We will not be adding a Ruby v2.3.1 image.

Hopefully you were able to find an alternative? Or were you able to bump of your requirement to use a newer Ruby release?

**Comment by owen-admedo** [comment]
Hi, we have managed to upgrade in the end.

Thanks for the response,
Owen
