### ISSUE TITLE
gcc images support

### ISSUE THREAD

**Issue by amazingguni** [circleci/circleci-images#285]
Hi, I'm using CircleCI Enterprise in samsung research :smile: 
Almost of our hardware projects are using c/c++ language.
There are official gcc images in dockerhub.
https://hub.docker.com/r/library/gcc/
So could you consider to add C/C++ docker image into `CircleCI predefined` image?

**Comment by felicianotech** [comment]
Hi @amazingguni,

I know it's been awhile. Is this still an issue for you?
We don't have a GCC image, but the `circleci/buildpack-deps` image has gcc installed: https://circleci.com/docs/2.0/circleci-images/#buildpack-deps
