### ISSUE TITLE
Install nvm in Node Image Variants

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#293]
Resulted from https://github.com/circleci/circleci-images/pull/276#issuecomment-442959478

**Comment by vvo** [comment]
Hey @iynere any news on bundling nvm in Circle CI images? Would you accept a pull request doing so?

Thanks!

**Comment by iynere** [comment]
@vvo likely won't happen with these images, but we're working on a new set of images to replace them & those _will_ include NVM:

https://github.com/search?q=topic%3Acimg+org%3ACircleCI-Public&type=Repositories

we are _just_ beginning to soft-alpha/beta these to get customer feedback—you can see what's been published here: http://hub.docker.com/r/circleciimages—& i don't believe we've published any node variants yet, but our new images are configured to use `nvm` for node variants by default
