### ISSUE TITLE
Terraform image?

### ISSUE THREAD

**Issue by nathanielks** [circleci/circleci-images#294]
Hi there!

I noticed there's a Terraform image on Docker Hub, but I don't see its Dockerfile in this repo. Is that publicly available anywhere?

**Comment by iynere** [comment]
hi @nathanielks, i believe that image is for our internal use, sorry for the confusion

there is a long-term goal to split out our usage of the `circleci` docker hub org—currently it's the home of our convenience images _and_ any (public) docker images that we use internally, which can be confusing for end users...

we don't currently provide a circleci-specific terraform docker image, but i imagine any community images would serve you well here—feel free to file a feature request for one, though:

https://circleci.com/ideas

there also appear to be some terraform orbs published by the community that could help you easily install & use terraform in your projects:

https://circleci.com/orbs/registry/?showAll=true (search 'terraform')

**Comment by nathanielks** [comment]
Ah, this is good to know, thank you! I'm currently using the terraform image, so I'll switch to another. Thanks @iynere 😄

**Comment by ryanwohara** [comment]
@nathanielks It's worth mentioning you can see some info about it with `docker history --no-trunc circleci/name:tag`

**Comment by nathanielks** [comment]
thanks @ryanwohara !

**Comment by iynere** [comment]
just to close the loop on this—

@nathanielks we've made the `circleci/terraform` image private, so folks won't get confused by it in the future 😄

**Comment by edahlseng** [comment]
Just filed a feature request: https://circleci.com/ideas/?idea=CCI-I-374

**Comment by iynere** [comment]
@edahlseng hmmm, that feature request is different than a circleci-customized terraform docker image.... can you say more about what you mean ?

**Comment by edahlseng** [comment]
@iynere it looks like the CircleCI ideas website does not update the query parameter in the address bar when navigating through certain flows - I ended up copying-and-pasting the wrong link! Just updated my comment above with the correct link.

**Comment by iynere** [comment]
ahhhh i see, ty !! @edahlseng
