### ISSUE TITLE
Docker image named `api-27-node8-alpha` upgraded to Node 10

### ISSUE THREAD

**Issue by daemonburrito** [circleci/circleci-images#297]
It seems like this might have been intentional*, but an image with the string `node8` in the name has been upgraded to Node 10, causing a bit of confusion for us.

Please either reply to this issue that no Node 8.x images will remain (and `node8` is a misnomer?) and close, or roll the NodeJS image back, if it was not intended.

Announcement:
* https://discuss.circleci.com/t/convenience-image-node-variants-updated/26834

**Comment by iynere** [comment]
@daemonburrito we've fixed this in staging but haven't yet merged the changes to master: https://github.com/circleci/circleci-images/blob/c180667df3fd6829a245d09dad9e8cfa9161bd44/android/generate-images#L24 we'll do that shortly

**Comment by daemonburrito** [comment]
Oh dear... I just realized that this means that there will be no Node 8.x convenience images generated? (if I read that right...). I'm afraid we have a hard dependency at the moment.

If that is the case, will the existing images with their history disappear (i.e., will pinning a sha not solve our problem temporarily)?

**Comment by iynere** [comment]
correct @daemonburrito 

we have been publicizing these changes for the past month, please see note from previous issue for info & workarounds:

https://github.com/circleci/circleci-images/issues/286#issuecomment-442890910
