### ISSUE TITLE
Support Android NDK r18b

### ISSUE THREAD

**Issue by guillaume-tgl** [circleci/circleci-images#302]
This new version of the NDK has been available since September so it would be great to have it available in an image. I could have submitted a PR where I would have replaced current version (r17b) by the latest version but I really think both should be available (actually r17c and r18b) since there has been lots of major changes (GCC and GNU STL have been removed) in this latest version.
I admit I'm not sure how to have multiple NDK versions available but if you give me some clue, I can try to submit a PR with this.

**Comment by iynere** [comment]
@guillaume-tgl adding both to one image would be a bit inefficient in that image size would go up a ton.... what we'd probably do is either:

1. stop building new v17 images (but the existing v17 images would continue to function as they do today) & going forward, only build v18 images

or

2. start building v18 images & also keep building v17 images & use separate tags for them

we're usually a bit wary about adding _more_ tags, b/c many of our images already have an overwhelming number of variants, but comparatively, android is actually pretty sparse, so building both might be ok

i'm not aware of any kind of ndk version manager that would let customers easily switch from one to another...

we'll look into this ! either way, if there's a new version, we should start building w/ it. thanks !

**Comment by guillaume-tgl** [comment]
Oh I wasn't thinking about keeping both versions into the same image, that would make no sense indeed. Maybe we can start by upgrading the NDK as you suggest in your first solution and see if there's a need to have both versions supported in separate images.

**Comment by iynere** [comment]
not sure if this will the final implementation but for now you can install any version you like this way @guillaume-tgl 

https://github.com/cci-orbs/circleci-images

**Comment by iynere** [comment]
closing anyway as we have an issue for a newer NDK version
