### ISSUE TITLE
alpine images

### ISSUE THREAD

**Issue by tsloughter** [circleci/circleci-images#315]
When making the PR to add Erlang images I attempted to include alpine images but as far as I can tell setting the alpine setting to `true` results in bad Dockerfiles because it still adds uses of `apt-get`. Did I miss something?

Oh, I did just notice in the README it is considered more of a thing for services and not for dev images. I'd gotten used to using alpine images for Circle, especially if building the release artifact for actual deployment (wanting a minimal image size).

**Comment by ryanwohara** [comment]
Alpine images are something we would ultimately like to support but right now the `apt-get` issue is a show stopper. We can theoretically add logic to support both apk and apt but it hasn't happened yet, unfortunately.

**Comment by tsloughter** [comment]
@ryanwohara ah, ok. Should I close this issue, or leave it open for others who might ask the same, until the scripts can use apk when alpine support is enabled?

**Comment by felicianotech** [comment]
I'll go ahead and close this. Alpine is on our internal tracker for if/when we decide to support it.
