### ISSUE TITLE
Android SDK license not accepted on api-27-alpha

### ISSUE THREAD

**Issue by MizzleDK** [circleci/circleci-images#323]
We haven't changed our setup and it was working just fine last week, but not this week. I've been tracking your attempts at fixing the errors, and none of the two fixes did anything for us.

It's using the latest image:
> Starting container circleci/android:api-27-alpha
  image is cached as circleci/android:api-27-alpha, but refreshing...
api-27-alpha: Pulling from circleci/android
Digest: sha256:772f61d984ffc57a7c99c41a393be6f39d9c514bd5825cf0c8060a65e2eb2f01
Status: Image is up to date for circleci/android:api-27-alpha
  using image circleci/android@sha256:772f61d984ffc57a7c99c41a393be6f39d9c514bd5825cf0c8060a65e2eb2f01

What went wrong:
> * What went wrong:
A problem occurred configuring project ':TVUniverse'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

Link to failed build (not public): https://circleci.com/gh/YouSee/android-tv-universe/5660

Is this because we're using platform 28 on an API 27 image? Like I said, it used to work, so I really didn't think too much about this, but maybe you fixed a bug in the previous images?

**Comment by sockeqwe** [comment]
Same here. Not sure why ... it just stopped working the other day ...

**Comment by juanimoli** [comment]
It looks like it got fixed it in [here](https://github.com/circleci/circleci-images/issues/249), but no release was made to [those images](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/android/images). Indeed, only api-27, api-27-node and api-27-ndk were released.

**Comment by iynere** [comment]
hi folks @sockeqwe @MizzleDK @juanimoli 

the issues you're seeing are the results of upstream changes to the android sdk manager

we patched them here: https://github.com/circleci/circleci-images/pull/320

you can see the latest images built here: https://hub.docker.com/r/circleci/android/tags

due to changes we announced late last year (link: https://discuss.circleci.com/t/convenience-images-update-upcoming-changes-to-android-images), we no longer build the `-alpha`-tagged images

if you'd like the new images that include the fixes for this issue, please use one of the tags from the docker hub link that was built in the last 24 hours (not `example` though please!)

thanks!

**Comment by iynere** [comment]
double-posting here for visibility : https://discuss.circleci.com/t/convenience-images-update-upcoming-changes-to-android-images/27003/4

**Comment by juanimoli** [comment]
@iynere Hey!

I found this doc: https://circleci.com/docs/2.0/circleci-images/#android, which doesn't specify which images had been deprecated. I wonder if you could please update this, for future usages.

Thanks :D

**Comment by iynere** [comment]
ahhhhh thank you so much @juanimoli i never look at that doc & totally missed it. will update it right now.

**Comment by iynere** [comment]
you can keep an eye on this @juanimoli 

https://github.com/circleci/circleci-docs/pull/3082

**Comment by juanimoli** [comment]
@iynere thanks for the quick response and solution :D
