### ISSUE TITLE
circleci/node:8-browsers toLocaleString bug

### ISSUE THREAD

**Issue by bartocc** [circleci/circleci-images#329]
One of my ember.js app tests running on `circleci/node:8-browsers` started failing yesterday, Wednesday Jan 30th, because `toLocaleString` started outputing a strange space character

Here is the failing test

```js
test('it renders', function(assert) {
  this.set('inputValue', '1234');

  this.render(hbs`{{format-currency inputValue}}`);

  assert.equal(this.$().text().trim(), "1 234,00 €");
});
```

And here is the failing output

```
not ok 86 Chrome 72.0 - helper:format-currency: it renders
    ---
        actual: >
            1 234,00 €
        expected: >
            1 234,00 €
        stack: >
```

At first sight, one might not understand why the test considers actual and expected to be different. The thousand separator is the culprit here. I hope it will be preserved after posting this issue on GH.

Here is the formatt currency function

```js
function formatCurrency([value]) {
  const formatted = Number(value).toLocaleString('fr', {minimumFractionDigits: 2});
  return `${formatted} €`;
}
```

Here is the last passing `Spin up environment`

```
Build-agent version 0.1.1480-7a5183d3 (2019-01-22T18:14:45+0000)
Starting container circleci/node:8-browsers
  image is cached as circleci/node:8-browsers, but refreshing...
8-browsers: Pulling from circleci/node
Digest: sha256:6210551cc4ef9725993180584ada8344400038675dc88d4339d1e828a0fe3913
Status: Image is up to date for circleci/node:8-browsers
  using image circleci/node@sha256:6210551cc4ef9725993180584ada8344400038675dc88d4339d1e828a0fe3913
```

And here is the first failing `Spin up environment`

```
Build-agent version 0.1.1480-7a5183d3 (2019-01-22T18:14:45+0000)
Starting container circleci/node:8-browsers
  image is cached as circleci/node:8-browsers, but refreshing...
8-browsers: Pulling from circleci/node
Digest: sha256:1abad858bc637b4b4c1dbcf3299791fcb9a08feb1b0ebe258fb277f36911a6c8
Status: Image is up to date for circleci/node:8-browsers
  using image circleci/node@sha256:1abad858bc637b4b4c1dbcf3299791fcb9a08feb1b0ebe258fb277f36911a6c8
```

Hope this helps

**Comment by bartocc** [comment]
Writing this issue helped me understand where the bug came from, Chrome 71 and Chrome 72 😱

I don't know why yet but toLocaleString behaves differently.

Hense, this is not a CircleCI bug. Closing.

Hope this will help others

**Comment by iynere** [comment]
glad you figured it out ! @bartocc

**Comment by thulioph** [comment]
How did you fix @bartocc ?

**Comment by bartocc** [comment]
@thulioph I did not really. I changed my test code
