### ISSUE TITLE
Ruby 2.6.1 Image

### ISSUE THREAD

**Issue by andrewmcodes** [circleci/circleci-images#330]
Is there any chance we can get the Ruby 2.6.1 Image added?

https://www.ruby-lang.org/en/news/2019/01/30/ruby-2-6-1-released/

Hoping this is the correct place to be asking for this, if not sorry!

Thanks all!

**Comment by iynere** [comment]
hi there @andrewmcodes 

we don't actively pick which versions of ruby to build—we generate our version tags from upstream sources

so when there's a 2.6.1 image here https://hub.docker.com/_/ruby (don't see one yet, at a glance), we will have one too

**Comment by molesky** [comment]
> so when there's a 2.6.1 image here https://hub.docker.com/_/ruby (don't see one yet, at a glance), we will have one too

Just wondering how long the delay usually is between the docker image and the circleCI image?  I'm waiting for ruby 2.5.4 which was released last week.  Thanks

**Comment by iynere** [comment]
hi @molesky see this blog post for details on our image-building schedule https://circleci.com/blog/build-image-update-schedule/
