### ISSUE TITLE
the executable file not found on jruby-9.2.6.0-jdk image

### ISSUE THREAD

**Issue by mengu** [circleci/circleci-images#338]
hello circlers

thank you for this fantastic tool. we are using the jruby-9.2.6.0-jdk image. the executable `file` is not shipped with this image. we need this executable because one of our gems `paperclip` use it behind the scenes. 

what would be the best way to quickly add it to the image? if you can lead me i can submit a PR.

thanks in advance.

**Comment by felicianotech** [comment]
Hi @mengu,

I don't see us adding this executable right now as we haven't had requests from others. There's three options for you here.

1. The upstream JRuby image is a Docker Community maintained image. Perhaps you can send a PR to that repo to see if they will add it. The repository you want to look at it here: https://github.com/cpuguy83/docker-jruby

2. Another option is to simply install it in your build at runtime. In any CircleCI step before you need to use it, run `apt-get install -y file`.

3. Create your own image based off our image that adds the executable.

I hope that helps.
