### ISSUE TITLE
apt 404ing

### ISSUE THREAD

**Issue by Naatan** [circleci/circleci-images#339]
I'm using the following images:

```
      - image: circleci/golang:1.9
      - image: circleci/postgres:9.6-alpine
```

Upon running `apt install postgresql-client` I get the following kinds of errors:

```Err:2 http://deb.debian.org/debian stretch/main amd64 libpython3.5-minimal amd64 3.5.3-1
  404  Not Found```

Looks like the image needs its mirrors updated?

**Comment by ryanwohara** [comment]
golang:1.9 looks pretty old. Use a newer tag (https://hub.docker.com/r/circleci/golang/tags) or just `apt-get update` in your config.

We will not republish 1.9 since upstream has already moved on.

**Comment by felicianotech** [comment]
@Naatan,

If you can use a new Go image, that's my suggestion. However the issue is that you're missing a command.

1. Don't use `apt` in a scripting environment, use `apt-get`.
2. You need to update the package index first.

The following will work in this image:

```
sudo apt-get update
sudo apt-get install -y postgresql-client
```

**Comment by Naatan** [comment]
Thanks, the update fixed it. Curious, what's the reason for using `apt-get` over `apt` in scripting environments?

**Comment by felicianotech** [comment]
It's just the way they were designed. Using `apt` directly can pull in brand new versions of a package while `apt-get` will only pull SRU bug fixes. So, in a scripting/headless/automated environment, `apt-get` is more stable to use.

I use Ubuntu on the desktop and there I use the newer `apt` all the time. It's just a tip to make your builds less likely to break in the future. :+1:

**Comment by Naatan** [comment]
Cool, did not know this, thanks!
