### ISSUE TITLE
Support Android NDK r19b 

### ISSUE THREAD

**Issue by CAMOBAP795** [circleci/circleci-images#341]
There is similar issue about r18b, but NDK r19b already available with https://github.com/circleci/circleci-images/issues/302

I plan to provide more generic approach, I will be glad to get some review/criticism

**Comment by iynere** [comment]
not sure if this will the the final implementation, but for now you can install any version of the ndk you'd like using this orb:

https://github.com/cci-orbs/circleci-images

**Comment by CAMOBAP795** [comment]
@iynere correct me if I'm wrong:
 - This solution will works only for circleci, so it's not 'docker level' solution
 - This will have serious performance impact during CI run

**Comment by iynere** [comment]
@CAMOBAP795 correct, this is limited to CircleCI, as orbs do not work anywhere else at the moment

in my tests (see https://circleci.com/workflow-run/454f22f9-eeb2-40c8-abe1-38241ff12515), installing the NDK at runtime only adds 20-30 seconds to the job, which isn't nothing but doesn't seem that bad to me

currently, we are working on an internal pilot for a brand-new set of circleci convenience images that will be more modular & easier to develop.... doing development on this repository is sometimes a frustrating / lengthy experience, so i wanted to ship something quickly that would work for folks in the interim

**Comment by CAMOBAP795** [comment]
@iynere thanks for answer

> installing the NDK at runtime only adds 20-30 seconds to the job

Absolutely agree with you, I'm going to close this issue

**Comment by iynere** [comment]
@CAMOBAP795 awesome, so happy to hear it :) 

i'll post a write up on using the orb to our discuss forum so we can get some more feedback
