### ISSUE TITLE
RubyGems CVE

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#343]
RubyGems needs to be updated to v3.0.3 due to a CVE. Waiting on upstream. This issue is just so that it's publicly known that we're tracking this.

Discussion: https://discuss.circleci.com/t/rubygems-vulnerability-march-2019/28854/2?u=felicianotech

Related PRs:

- https://github.com/docker-library/ruby/pull/271 (passed/merged)
- https://github.com/docker-library/official-images/pull/5521 (passed/waiting)

**Comment by felicianotech** [comment]
Updated images have been published.

**Comment by bbugh** [comment]
Will 2.6.2 and 2.5.4 be added as well?

2.6.2 is on docker https://github.com/docker-library/official-images/pull/5542

(it happened just a minute ago though).

Not sure if how much of this process is automated.

**Comment by felicianotech** [comment]
It will be added soon. Here's the process: https://circleci.com/blog/build-image-update-schedule/

**Comment by bbugh** [comment]
Awesome, thank you!

**Comment by taylorthurlow** [comment]
Docker has had 2.6.2 images for a while, it should fall under the automated (<24h) category I assume? I'm not seeing anything yet.

**Comment by felicianotech** [comment]
@taylorthurlow How are you "looking"? We've had it for a bit as well.

**Comment by taylorthurlow** [comment]
@felicianotech I was looking at [this endpoint](https://circleci.com/docs/2.0/docker-image-tags.json). I just tried using the image though, and it seems to work.

Thanks for the heads up!

**Comment by felicianotech** [comment]
@taylorthurlow Ah. That JSON file doesn't currently get updated as often as our images are published. Opening a PR now to fix that.

**Comment by bbugh** [comment]
@felicianotech thank you for the clarity on the json file, I have also been waiting for that to update, based on the documentation `Recent Tags: (View all available image tags here)`. 

Glad that it's working now, either way. Thanks all!

**Comment by felicianotech** [comment]
PR merged.
