### ISSUE TITLE
Generate images for latest node LTS (10.15.3)

### ISSUE THREAD

**Issue by jhoch** [circleci/circleci-images#344]
I was looking to make a pull request, but it looks like these are generated dynamically.  Does something just need to be kicked off?

**Comment by felicianotech** [comment]
Our images are based off of upstream images. The Node v10 update was merged about 20 hours ago: https://github.com/docker-library/official-images/pull/5519

It should be hitting our images today. (our update process is 24-48 hours after upstream)

**Comment by jhoch** [comment]
Makes sense!  Thanks for the explanation.
