### ISSUE TITLE
Images for older Ruby versions

### ISSUE THREAD

**Issue by bquorning** [circleci/circleci-images#347]
When working on Ruby libraries that are compatible with older versions of Ruby, it is necessary to test with e.g. Ruby 1.9 and Ruby 2.0. I saw in #330 that you don’t actively pick which versions to build – you just depend on the available tags on https://hub.docker.com/_/ruby.

Well, there are images available for `ruby:1.9` and `ruby:2.0`. Would it be possible to have images for `circleci/ruby:1.9` and `circleci/ruby:2.0` too?

**Comment by felicianotech** [comment]
Our images only build for recent releases of Ruby. I'd suggest basing your own image off of one of those upstream Ruby images you've mentioned. Here's a list of tools we pre-install if you want to go this route: https://circleci.com/docs/2.0/circleci-images/#pre-installed-tools
