### ISSUE TITLE
circleci/node:10.15.3-browsers different in local and ci

### ISSUE THREAD

**Issue by HsuTing** [circleci/circleci-images#354]
I use testcafe in circleci. It work in `circleci/node:10.15.3-browsers` locally, but it throw error in `circleci`. I do not have any idea why error cause this. Here is my config:

```
...
  docker:
    - image: circleci/node:10.15.3-browsers
  working_directory: ~/repo
...
```

**Comment by felicianotech** [comment]
Hi,

What is the error?

**Comment by HsuTing** [comment]
The behavior is different between image `circleci/node:10.15.3-browsers` in local and circleci.

**Comment by HsuTing** [comment]
I found the problem was caused by other code error, not circle.
Sorry. Thank for your answer 😅.
