### ISSUE TITLE
-browsers variant does not include latest version of Chromedriver

### ISSUE THREAD

**Issue by tjvc** [circleci/circleci-images#355]
Chromedriver has switched to a new versioning system that matches Chrome's version numbers.

The Ruby browsers images determine which version of Chromedriver to install by requesting https://chromedriver.storage.googleapis.com/LATEST_RELEASE, e.g.:

https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/ruby/images/2.4.5-stretch/node-browsers/Dockerfile#L57

But this URL no longer returns the latest version:

> The https://chromedriver.storage.googleapis.com/LATEST_RELEASE file is a legacy leftover from the old release model, and will stay at 2.46 for the next few months (to support apps that haven't been updated to use the new version numbers), and then removed completely.

https://groups.google.com/forum/#!topic/chromedriver-users/8VmMaFjs1cg

Could the build images be updated to install the latest Chromedriver version?

**Comment by felicianotech** [comment]
Related: #351, #352.

**Comment by felicianotech** [comment]
We need to append the major version of Chrome to the URL `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_` to get the new Chromedriver version number.

We should also pin major Chrom version numbers as well while we're doing this. @iynere?

**Comment by iynere** [comment]
since chromedriver & chrome are now version-locked, it makes sense to use 1 variable to track that, so that we always keep them in lock-step @felicianotech

**Comment by iynere** [comment]
@jkzilla / @BoVice were talking about taking this PR on @felicianotech

**Comment by iynere** [comment]
https://github.com/circleci/circleci-images/pull/358 fixes this

**Comment by agustinf** [comment]
Version 76 of Chrome and chromedriver have come out but circleci/ruby:2.5.5-node-browsers produced an error that reads `Chrome version must be between 71 and 75`
