### ISSUE TITLE
"chrome not reachable" with chromedriver in circleci/ruby

### ISSUE THREAD

**Issue by kolen** [circleci/circleci-images#357]
All tests that use selenium with chromedriver in `circleci/ruby:2.4-stretch-node-browsers` image started to fail with following error about 3 days ago:

```
MyTest#my_test_method:
Selenium::WebDriver::Error::WebDriverError: chrome not reachable
  (Session info: headless chrome=73.0.3683.75)
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-141-generic x86_64)
    (...stacktrace...)
```

Versions, which are known to be broken: `ef5a9016296296ec66546581813f97ada9ba897cca2c0a2affb439d68fd77eec`, `8c0c0dbb1d8d0e3158e6489e1b3bfa1cdcc9bd215376f19c917b93d1db28a786 `
Last working version: `e8bded1fa294b86de4f02e6e9169f5b72c4f45c0e910624e097f0cf271b7bc73` (we had last build at 15 march 13:44 UTC which used it)

As a workaround, it's possible to specify `image: circleci/ruby:2.4-stretch-node-browsers@sha256:e8bded1fa294b86de4f02e6e9169f5b72c4f45c0e910624e097f0cf271b7bc73` to pin old version of image.

Might be related to #355, #352

**Comment by iynere** [comment]
gonna close this in favor of https://github.com/circleci/circleci-images/issues/355 @kolen 

a fix is in-progress, thank you !
