### ISSUE TITLE
CircleCI gotestsum permissions different in circleci/golang:1.11.4 vs 1.11.5

### ISSUE THREAD

**Issue by alvin-huang** [circleci/circleci-images#365]
Thanks very much for the update here: https://github.com/circleci/circleci-images/pull/348! I had quite a hack around this to do some nasty `sed` that I can now take out 😄. 

It looks like the tool was only updated on circleci:golang:1.11.5 and not on 1.11.4 though. Also the permissions for the binary on 1.11.4 were `circleci:circleci` and on 1.11.5 it was `root:root`. This means if you all forget to update the tool in the future, I can't run the same curl and replace the binary (of course I can put it somewhere else though).

**Comment by felicianotech** [comment]
@dnephin Any idea why this may be? I have #418 open to update it again. Any other changes we need to make?

**Comment by felicianotech** [comment]
Okay I'm going to close this.

@alvin-huang 

> It looks like the tool was only updated on circleci:golang:1.11.5 and not on 1.11.4

That's how CircleCI Convenience Images work. Unless there's a major bug or security issue, older images won't get updated. Only a few recent point releases get updated. This is to prevent us updating older images that then break someone's long-time builds.

The user/group will remain the same for this tool. Please keep in mind that the `circleci` user in our containers has passwordless sudo so you still have access to update this binary during a build if you want.
