### ISSUE TITLE
OpenJDK 8 Can't Be Installed in -browsers variant

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#366]
The OpenJDK 8 packages such as `openjdk-8-jdk` or `openjdk-8-jre` can't be installed in our `-browsers` variants anymore causing several jobs to fail.

The issue? On March 20th [Debian decided to move Wheezy and Jessie backport repositories to the archive](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html). We are using the OpenJDK 8 packages from Jessie Backports.

I see three solutions for this.

1. Stop building Debian Jessie images. The main release of Debian 8 was EOL is 2018. While there still is the LTS project, it doesn't cover backports. https://wiki.debian.org/DebianReleases
2. We can switch to using the Jessie Backports Archive URL. This will then continue to work as expected, but packages in the Archive infrastructure are not maintained. This means no security updates at all.
3. We stop using OpenJDK 8 at all and use a newer version. OpenJDK is currently at v12, 8 is very old. This option isn't mutually exclusive to option 1.

I'll make PRs for the first two options and we can discuss from there which way to go.

**Comment by henrich** [comment]
Debian9 "stretch" has [openjdk-8](https://packages.debian.org/source/stretch/openjdk-8), why don't you switch to the current stable version? And maybe archive.debian.org doesn't have enough resource to provide such traffic.

Thank you for using Debian :)

**Comment by felicianotech** [comment]
@henrich Hi. Upstream, official Docker Library images determine what base OSs are used. They are using both Debian 9 and 8 right now.

Debian is great! :+1:

**Comment by felicianotech** [comment]
@iynere Merging PR for solution # 2 at this point as more people are affected by this issue due to the weekday starting.
