### ISSUE TITLE
New #269 error with upstream issue with the Debian mirrors

### ISSUE THREAD

**Issue by Akecel** [circleci/circleci-images#370]
#269

**Comment by Akecel** [comment]
``` #!/bin/bash -eo pipefail
sudo apt-get -y -qq update
sudo apt-get install python-pip python-dev build-essential
sudo pip install awsebcli --upgrade
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code 100

**Comment by felicianotech** [comment]
This issue is being handled with the PR #368. New images will be available soon.

**Comment by felicianotech** [comment]
I'm going to leave this open for now so that anyone coming here can see this. I'll close this issue once updated images have been published.

**Comment by Blokh** [comment]
This issue is still happening

**Comment by Akecel** [comment]
> This issue is still happening
Thar will be fixee today.
You juste have to use a non-Jessie version  of your image if you can't wait.
That should avoid this issue entirely.

**Comment by Blokh** [comment]
Alright, Thanks

> > This issue is still happening
> > Thar will be fixee today.
> > You juste have to use a non-Jessie version  of your image if you can't wait.
> > That should avoid this issue entirely.

**Comment by martinezcoder** [comment]
Yes, I was using ` - image: ruby:2.3.1`. It works now after changing it to `- image: ruby:2.3.8-stretch`

**Comment by zsoobhan** [comment]
FYI alternative images and their tags can be found [on this page](https://circleci.com/docs/2.0/circleci-images/)

**Comment by felicianotech** [comment]
Follow up and resource can be found [here](https://discuss.circleci.com/t/apt-get-update-failing-on-debian-8-jessie-based-convenience-images/29257?u=felicianotech).

**Comment by Akecel** [comment]
For php i use 

> - image: circleci/php:7.1-node-browsers

**Comment by felicianotech** [comment]
Can anyone still using the jessie images confirm that with a new build, they're working now?

**Comment by juny4ng** [comment]
@felicianotech still happening for us

![image](https://user-images.githubusercontent.com/3325766/55007884-2107a900-501b-11e9-9ceb-f3ebd3a34cf2.png)

**Comment by felicianotech** [comment]
@juny4ng Without seeing the SHA1 for that image, those URLs look like that's the old image. Most likely, the host that ran that build cached it.

**Comment by BlaneCordes** [comment]
what is the proper way, rebuild without cache?

**Comment by Akecel** [comment]
> what is the proper way, rebuild without cache?

No you just need to use the same image you already use but without jessie.

For exemple for php : 

``` circleci/php:7.1-jessie-node-browsers 

Become 

``` circleci/php:7.1-node-browsers 

You just have too find your image without jessie

**Comment by BlaneCordes** [comment]
yea i was referring to the question for us to try rebuilding with Jessie. I still had issue as well.

I switched to ruby:2.4.1-stretch-node-browsers but that creates puma install issues now

**Comment by juny4ng** [comment]
> @juny4ng Without seeing the SHA1 for that image, those URLs look like that's the old image. Most likely, the host that ran that build cached it.

`Status: Downloaded newer image for circleci/ruby:2.3.4-node-browsers
  using image circleci/ruby@sha256:4be65b406f7402b5c4fd5df7173d2fd7ea3fdaa74d9c43b6ebd896197a45c448`

**Comment by felicianotech** [comment]
@juny4ng Ah, you're using an old image. That won't get updated regardless.

Try using the latest point release of Ruby v2.3, or the alias tag. So one of these two:

```
circleci/ruby:2.3.8-node-browsers
circleci/ruby:2.3-node-browsers
```

**Comment by nachomazzara** [comment]
Is failing also for this ones too:

```
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      - image: circleci/postgres:9.6
...
```

**Comment by feitla** [comment]
failing for
```
docker:
      - image: circleci/node:10.11.0
``` 
as well

**Comment by jesslarson** [comment]
Also failing for 
`    docker:
      - image: circleci/python:2.7.14`

**Comment by mogurbon** [comment]
also for 
` docker:
      - image: circleci/node:8.1.4`

**Comment by jonnyhork** [comment]
Just to add to the record I also notice this problem with `- image: circleci/node:8.10.0-browsers`

**Comment by dodunsec** [comment]
in my case, changed
  deploy:
      working_directory: ~/repo
      docker:
        - image: circleci/ruby:2.4.1-node-browsers
to
        - image: circleci/ruby:2.4.1-stretch-node-browsers
and all is now working okay

**Comment by IvanK88** [comment]
The same problem with `- image: 'circleci/node:9.11.1'`

**Comment by fredhope2000** [comment]
@jesslarson changing `circleci/python:2.7.14` to `circleci/python:2.7.14-stretch` fixed the issue for me

**Comment by tedWexus** [comment]
When should we expect #368 to be deployed? Do we have to change our images to the `stretch` versions even with the updates?

**Comment by snird** [comment]
Still not working with ruby 2.4.1

**Comment by jimjeffers** [comment]
I'm also having the same issue with `circleci/ruby:2.2-node-browsers`

**Comment by tedWexus** [comment]
I am still having the same issue with `circleci/ruby:2.2.10-node-browsers`. No "stretch" version is available for this image.

**Comment by tedWexus** [comment]
>I am still having the same issue with circleci/ruby:2.2.10-node-browsers. No "stretch" version is available for this image.

Upgrading my Ruby version and using a `stretch` image works:
```
circleci/ruby:2.2.10-stretch`node-browsers
```

Unfortunately, changing the Ruby version has introduced various errors in my app 😛

**Comment by saurabhbhatia** [comment]
Still failing

**Comment by chenhoward** [comment]
> > I am still having the same issue with circleci/ruby:2.2.10-node-browsers. No "stretch" version is available for this image.
> 
> Upgrading my Ruby version and using a `stretch` image works:
> 
> ```
> circleci/ruby:2.2.10-stretch`node-browsers
> ```
> Unfortunately, changing the Ruby version has introduced various errors in my app 😛

I'm trying to use a 2.2.10 but `circleci/ruby:2.2.10-stretch-node-browsers` did not work for me (assuming the backtick in your code block is a typo)

**Comment by tedWexus** [comment]
> > > I am still having the same issue with circleci/ruby:2.2.10-node-browsers. No "stretch" version is available for this image.
> > 
> > 
> > Upgrading my Ruby version and using a `stretch` image works:
> > ```
> > circleci/ruby:2.2.10-stretch`node-browsers
> > ```
> > Unfortunately, changing the Ruby version has introduced various errors in my app 😛
> 
> I'm trying to use a 2.2.10 but `circleci/ruby:2.2.10-stretch-node-browsers` did not work for me (assuming the backtick in your code block is a typo)

@chenhoward Sorry! That was a typo. I meant to write `2.4.5-stretch` instead of `2.2.10-stretch`. The latter image does not exist. Here is the list of available images:
https://circleci.com/docs/2.0/docker-image-tags.json

**Comment by chenhoward** [comment]
> > > Upgrading my Ruby version and using a `stretch` image works:
> > > ```
> > > circleci/ruby:2.2.10-stretch`node-browsers
> > > ```
> > > Unfortunately, changing the Ruby version has introduced various errors in my app 😛
> > 
> > 
> > I'm trying to use a 2.2.10 but `circleci/ruby:2.2.10-stretch-node-browsers` did not work for me (assuming the backtick in your code block is a typo)
> 
> @chenhoward Sorry! That was a typo. I meant to write `2.4.5-stretch` instead of `2.2.10-stretch`. The latter image does not exist. Here is the list of available images:
> https://circleci.com/docs/2.0/docker-image-tags.json

Thanks! For a sec I thought there were secret images I didn't have access to.

**Comment by eliduke** [comment]
`circleci/ruby:2.3-node-browsers` seems to be working for me. It does cause some issues with specific gem versions and the whatnot, but at least it gets past the "Install native test dependencies" phase.

**Comment by martinezcoder** [comment]
@eliduke I had the same problem when I changed to `- image: ruby:2.3.8-stretch`.

I had some issues with specific versions and I fixed it this way:

* Remove parallelism in bundle. I remove this line from my config.yml:

```
- BUNDLE_JOBS=3
```

If the problem persists, you can try the following:


1. Force circleci to use the same version of bundle specified in my `Gemfile.lock``

```
gem install bundler -v1.6
```

3. Retry bundle install

```
bundle install --retry 3
```

I hope you will fix the problem just removing the `BUNDLE_JOBS` part

https://bundler.io/v1.5/whats_new.html

**Comment by benoittgt** [comment]
We are still having the issue with `circleci/node:8.10.0-browsers` :/

**Comment by jonnyhork** [comment]
@benoittgt If you use `circleci/node:8.10.0-stretch-browsers` then it should work for you. If you look at the [Dockerfile](https://github.com/CircleCI-Public/circleci-dockerfiles/blame/master/node/images/8.10.0/browsers/Dockerfile#L9) for the `node:8.10.0` base image it uses Jessie, so it sounds like you should avoid that all together.

**Comment by felicianotech** [comment]
Closing this now.

The general idea here, use a newer point release of the image and use Debian Stretch (not Jessie) based images.
