### ISSUE TITLE
Request: Add ~/.local/bin to default PATH?

### ISSUE THREAD

**Issue by PiDelport** [circleci/circleci-images#375]
Background: https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#~/.local/bin/

A number of developments tools (such as `pip install --user`) will use the `~/.local` prefix and install executables into `~/.local/bin`, which is part of the default PATH on many modern operating system distributions.

It would be great if the CircleCI images include this by default, so that jobs can make use of it without having to manually add the missing PATH entry first.

### Upstream Debian bug

* [#839155 - bash: $HOME/.local/bin missing from $PATH again - Debian Bug report logs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839155)

Debian fixed this, but it's not in the Debian stretch release that's used by the upstream Docker images.

However, waiting for this upstream fix to reach the CircleCI images won't quite be enough, either, because the fix only adds the path entry if the directory already exists. This conditional logic may make sense for Debian's default interactive user experience, but it means the PATH entry will still be missing for new CircleCI containers. So, this should still be worth addressing in the CircleCI base images.

**Comment by iynere** [comment]
thank you !! @PiDelport 

hmm, i'm not sure this would actually be the right place to fix this.... i don't think we configure PATH within our docker images, i think it's something that we inject into jobs & configure internally, or perhaps some combination of the two.... @felicianotech do you know ?

that said, either way, it's worth pointing out that this is something folks can easily work around by simply creating the directory & manually setting PATH in their jobs

**Comment by iynere** [comment]
here's our documentation on how one would do that, as well:

https://circleci.com/docs/2.0/env-vars/#using-bash_env-to-set-environment-variables

**Comment by PiDelport** [comment]
Hi @iynere!

I looked at how this might be implemented: how does #377 look to you?

**Comment by PiDelport** [comment]
I think this is worth addressing in CircleCI because the `~/.local` prefix is increasingly becoming a standard that vendors, tools, and users expect to work by default.

This is what things like [PEP 370](https://www.python.org/dev/peps/pep-0370/) and `pip install --user` rely on, and it's really useful for things like for bootstrapping CI builds with just a `pip install --user tox`.

(Note also that `--user` is slated to become the default behaviour of `pip install`: see <https://github.com/pypa/pip/issues/1668> and <https://github.com/pypa/pip/issues/4575>.)

This is my current workaround, but it's a papercut I'd really like to avoid having to repeat for every project:

```yaml
jobs:
  build:
    environment:
      # XXX: https://github.com/circleci/circleci-images/issues/375
      PATH: '/home/circleci/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
```

**Comment by iynere** [comment]
totally, tysm ! @PiDelport i'll respond on the PR :)
