### ISSUE TITLE
circleci/openjdk:12

### ISSUE THREAD

**Issue by iamdanfox** [circleci/circleci-images#389]
JDK 12 reached General Availability on 19 March 2019 (https://openjdk.java.net/projects/jdk/12/), binaries available here: https://jdk.java.net/12/.

Any chance we can get the usual suite of circleci/openjdk:{12, 12-node, etc etc} images published?

Until then, I'm just using the official `docker pull openjdk:12` image, but I'd love to use a consistent circleci one that has the right user set up and git/ssh installed etc!

**Comment by iynere** [comment]
hi @iamdanfox 

as you can see [here](https://hub.docker.com/_/openjdk), for JDK 12, Docker's official openJDK image has shipped only variants based on Alpine, Oracle Linux, and Windows Server

all of our images are Debian/Ubuntu based, so we cannot extend OpenJDK 12 with our current image-building infrastructure, not to mention doing so would no longer provide much of a unified customer experience :/

we're working on a few different short-, medium-, & longer-term solutions to work around this problem, which we'll be posting a longer, more official write-up about later today or tomorrow—you will be able to find it here: https://discuss.circleci.com/tags/convenience-images

briefly, we will be providing a way for folks to use any JDK 12 image and layer on the CircleCI customizations/tools we install in our various variants (Node, browser tools, etc.) at runtime via an [orb](http://circleci.com/orbs)

in the medium-term, i believe the upstream issue will be rectified as of JDK 13

in the longer-term, we will be building an OpenJDK image from scratch, to mitigate upstream issues such as this one

thanks !!
