### ISSUE TITLE
Alpine-based images

### ISSUE THREAD

**Issue by phawxby** [circleci/circleci-images#390]
I'm opening this as a new ticket as there has been no response to my comments on the previously closed ticket #158.

We're in need of Alpine based node images although I imagine there are other cases for them too. We use CircleCI to deploy to Azure, it builds a zip asset which is deployed. The built asset contains all node dependencies because Azure doesn't support yarn and we want to have a complete zip file should we even need to roll back based on a zip in future and a dependency [has gone missing](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/). 

Azure AppService is hosted on a MUSL based Linux (I assume Alpine) meaning when the `yarn install` occurred on CircleCI it installed the wrong binaries for [sharp](https://www.npmjs.com/package/sharp). This broke our development tier and threw our testing strategy into doubt as it has passed on CircleCI.

As [CircleCI provides Orbs](https://circleci.com/orbs/registry/orb/circleci/azure-cli) for connecting to Azure this use case isn't an unexpected one. As a result I think Alpine based images are a necessary addition.

**Comment by iynere** [comment]
hi @phawxby 

extending this codebase to more explicitly / broadly support alpine would be difficult, as we actually don't currently make any decisions about what linux distros to use in our images, but rather extend the official Docker Library images:

https://github.com/circleci/circleci-images#official-images

to that point, some of the docker library images _do_ build alpine variants—you can find our extended versions of them by searching our tags list for `alpine`:

https://circleci.com/docs/2.0/docker-image-tags.json

unfortunately, it seems that the community maintainers of the upstream node.js docker image do not build alpine-based variants... that said, you should be able to use any of our `-alpine`-tagged image variants—or any alpine-based docker image, generally—and use our `circleci/node` orb to quickly/easily install node.js in your job at runtime:

https://circleci.com/orbs/registry/orb/circleci/node#commands-install

going forward, we are working on a rebooted set of convenience images that we will build from scratch, where we will be able to be much more opinionated about how we design / structure our images, what distros we support, etc.—but that work is still a few months away from being ready for customers to try out 🙂 

please give that orb a shot, though, & [file an issue against the repository](http://github.com/circleci-public/node-orb) if you run into any problems with it—want to make sure that the logic there works on as many different types of linux systems as possible 🙂

**Comment by phawxby** [comment]
Ok, then limiting the issue to our specific problem for now, docker does have official Alpine images for node. How hard would it be to introduce them?

I am concerned that using a completely unrelated image then installing node could introduce the same kind of issues.

**Comment by iynere** [comment]
ahhh, thank you for your persistence @phawxby & good find

it looks like we actually can quickly / easily choose to start including those upstream alpine variants in our builds by setting this environment variable in our node job:

https://github.com/circleci/circleci-images/blob/dccd168475e10183b41578bec97bcdf8d748b200/shared/images/generate.sh#L12

let me look into this & try it out on a branch. i'll ping you on a PR so you can follow.
