### ISSUE TITLE
Golang images don't include all `go get` supported VCS clients.

### ISSUE THREAD

**Issue by MrJoy** [circleci/circleci-images#394]
The `go get` command supports Git, Mercurial, Bazaar, and SVN: https://github.com/golang/tools/blob/master/go/vcs/vcs.go#L66

The golang Docker images being generated don't include Bazaar or SVN clients, which means that it's possible that some orgs will run into compatibility problems, depending on what libraries they're referencing.

Granted, this is a relatively minor concern in terms of breadth of impact -- and it's not affecting me personally, but I happened to notice it in passing and thought it might be worth giving you a heads-up over, in the off chance that addressing it is reasonably trivial.

**Comment by felicianotech** [comment]
True but so far we haven't had anyone using this image express a need for this. The rare person who would can simply `apt-get install bzr svn` during a build if they need it.

If in the future we see a large percentage request this, it's definitely something we can revisit.
