### ISSUE TITLE
Question: When do you updates for google-chrome and chromedriver?

### ISSUE THREAD

**Issue by toriumi0118** [circleci/circleci-images#397]
Hi.

I'm using a `circleci/ruby:2.5.0-node-browsers` image and using a chrome-driver in our product for testing. Also I'm using a  chrome-driver for version `ChromeDriver 74.0.3729.6` in a local machine.

However, the image provided seems to use `Google Chrome 64.0.3282.186` and `ChromeDriver 2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7)`.

```
$ docker run -it circleci/ruby:2.5.0-node-browsers bash
circleci@1a4f2b18ace9:/$ _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

circleci@1a4f2b18ace9:/$ chromedriver -v
ChromeDriver 2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7)
circleci@1a4f2b18ace9:/$ google-chrome --version
Google Chrome 64.0.3282.186
```

I found some PullRequests and Issues related by this.

- https://github.com/circleci/circleci-images/pull/174
  It said you needed to pin the version of chorme, and currently this image has been used.
- https://github.com/circleci/circleci-images/issues/355
- https://github.com/circleci/circleci-images/pull/358

Then, the last PullRequest has fixes to update the versions of chrome and chrome-driver, and it has been merged. However, I could not point the image to use newer chrome-driver in CircleCI process, so I added some command to install newer chrome and driver with a base of `-browser` image by myself. 

I'm just wondering when to release the newer one.

**Comment by iynere** [comment]
@toriumi0118 we likely won't be modifying how we install chrome / chromedriver in these images, as we're working on a new set of images that will address these types of issues in a better way, but you can use some orbs we'e been rolling out as part of that work to install newer versions of chrome / chromedriver:

https://circleci.com/orbs/registry/orb/circleci/circleci-images

**Comment by toriumi0118** [comment]
I see. thanks!
