### ISSUE TITLE
ChromeDriver version installed is beta, not latest stable

### ISSUE THREAD

**Issue by PhilCoggins** [circleci/circleci-images#399]
https://discuss.circleci.com/t/docker-image-installing-beta-version-of-chromedriver/30723

image: circleci/ruby:2.6.3-node-browsers

According to http://chromedriver.chromium.org/home, this is NOT a stable release

```
$ chromedriver --version
ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40})
```

**Comment by iynere** [comment]
thank you ! @PhilCoggins

**Comment by felicianotech** [comment]
@PhilCoggins Perhaps they were slow to update their website? It says it's stable when I looked.

**Comment by felicianotech** [comment]
Here's where we install Chrome, which is a stable package straight from Google: https://github.com/circleci/circleci-images/blob/staging/shared/images/Dockerfile-browsers.template#L45

I think the issue may have been that the Chromium website gets updated slowly after the Chrome Team pushes stable builds.
