### ISSUE TITLE
Bump docker to 18.09

### ISSUE THREAD

**Issue by mohsen0** [circleci/circleci-images#408]
Hi

Can we upgrade docker cli to 18.09?

Thanks

**Comment by felicianotech** [comment]
@mohsen0 Which image are you currently using? I just checked a few of our images and they all have Docker v18.09.6.

**Comment by mohsen0** [comment]
I made a mistake, the version is fine,
Sorry

**Comment by felicianotech** [comment]
Oh okay no problem.
