### ISSUE TITLE
rsync missing in 'circleci/php:7.1'

### ISSUE THREAD

**Issue by danielbachhuber** [circleci/circleci-images#417]
Here's our first failed build: https://circleci.com/gh/pantheon-systems/wp-redis/1434

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/36432/61214823-d12e1a00-a6bd-11e9-9ddc-9842ef406e6f.png">

Maybe something changed about these common extensions?

https://github.com/circleci/circleci-images/blob/5e43e27c17eef8e2a3c58d47fa1fbaa67d96069d/php/generate-images#L22-L24

**Comment by ryanwohara** [comment]
Kind of seems like something changed upstream. I don't see anything on our end installing rsync.

I advise installing it yourself in your script.

**Comment by danielbachhuber** [comment]
> I advise installing it yourself in your script.

Works for me, thanks.
