### ISSUE TITLE
Missing circleci/node:10.16.1  image

### ISSUE THREAD

**Issue by johnjensenish** [circleci/circleci-images#419]
[node.js 10.16.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-07-31-version-10161-dubnium-lts-bethgriggs) was released on July 31, 2019.  Please add an image for this release: `circleci/node:10.16.1`

**Comment by felicianotech** [comment]
Hey @johnjensenish,

This image is already available but please take a look at this blog post for our image build process: https://circleci.com/blog/build-image-update-schedule/
