### ISSUE TITLE
timeouts when trying to start a selenium driver

### ISSUE THREAD

**Issue by jonathanong** [circleci/circleci-images#42]
we've been experiencing timeouts when trying to use the driver. this has been the error for ember tests: https://github.com/testem/testem/issues/1021#issue-190469968

we've seen it for selenium tests, but we just added a timeout and retry for loading the driver and our tests pass.

this comment https://github.com/testem/testem/issues/1021#issuecomment-312616817 says that it may be a Xvfb issue.

any insight on what may cause this? we've seen this in circle 1 for quite a while and we also see it in circle 2. we are using `circleci/node:7-browsers`

**Comment by ryanwohara** [comment]
Try binding to 127.0.0.1 instead of localhost wherever possible and try different versions of Selenium. The current configuration of the images is the most versatile combination we've found.
