### ISSUE TITLE
Latest commit to the image broke our GNUPG tests

### ISSUE THREAD

**Issue by AlexandrePilon** [circleci/circleci-images#429]
In this [Commit](https://github.com/circleci/circleci-images/commit/0852b22223de98dab13bc97470019476202c63cf) you changed the Home path. 
Since then our PHPunit test that uses GNUPG stopped working and is returning this error
`The 'homedir' "/home/circleci/.gnupg" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory.`

I honestly have no clue what should be done to fix it.  Any Idea ?

**Comment by felicianotech** [comment]
Hi @AlexandrePilon,

Are you using the `circleci` user in your build? Or perhaps something else? Is there any portion of the config here you can share?

**Comment by AlexandrePilon** [comment]
Hi @felicianotech yes we are using the php:7.2-stretch-node image

We were able to fix it by changing the user, I thought the folder would not be correct but apparently using superuser was enough.

**Comment by felicianotech** [comment]
Cool. regardless, I've simplified the commit by not specifying a new $HOME. This change is rolling out now (give it an hour). So either way your build should behave as it were.

Let us know if that isn't the case. Thanks.

**Comment by AlexandrePilon** [comment]
@felicianotech I retried the tests with the change you made and our old code still does not work but the sudo solution we had still worked. The new error we got was the GPG key could not be found.
