### ISSUE TITLE
Provide a license

### ISSUE THREAD

**Issue by string-areeb** [circleci/circleci-images#434]
I cannot see a license of the project. Are the images free to use in other CI services like GitLab or GitHub Actions?

Please provide info so that it is clear what is permitted and what is not.

Thanks

**Comment by felicianotech** [comment]
Good point. This will be done today. :+1:

**Comment by felicianotech** [comment]
@string-areeb Actually, the license is already mentioned in both the readme as well as the standard license file right in the repo.

**Comment by felicianotech** [comment]
I did however make a PR that addresses using the Docker image wherever you want. I believe this was implied anyway, but not it's explicit.

**Comment by string-areeb** [comment]
I don't know how I missed the LICENSE, sorry :man_facepalming: And thanks for responding so quickly

**Comment by felicianotech** [comment]
No problem. :)
