### ISSUE TITLE
PostgreSQL 12

### ISSUE THREAD

**Issue by mattbretl** [circleci/circleci-images#441]
PostgreSQL 12 was released last week. Could you please re-enable the builds which were disabled during beta? Thanks!

**Comment by felicianotech** [comment]
Yup - sounds good. As long as it passes our build tests, it should be available within 24 hours. I'll update this Issue when it is.

**Comment by felicianotech** [comment]
This isn't closed yet as I ran into an issue with PostGIS and PostgreSQL 12 but still working on it.

**Comment by felicianotech** [comment]
@mattbretl The PostgreSQL v12 image is available is production as of yesterday morning.
