### ISSUE TITLE
`generate_dockerfiles` CI job fails

### ISSUE THREAD

**Issue by n6g7** [circleci/circleci-images#445]
For the past 5 days, the `generate_dockerfiles` job of the `build_test_deploy` has been failing:

- https://circleci.com/gh/circleci/circleci-images/27714
- https://circleci.com/gh/circleci/circleci-images/27715
- https://circleci.com/gh/circleci/circleci-images/27716
- https://circleci.com/gh/circleci/circleci-images/27717
- https://circleci.com/gh/circleci/circleci-images/27718

Apparently git isn't properly configured.

While this is being resolved,  any chance we could do a manual deployment so we can get that sweet python 3.8 image? :)

**Comment by felicianotech** [comment]
I don't want to stand in the way of anyone's Python goodness. :relaxed:

I'll see what I can do.

**Comment by felicianotech** [comment]
`circleci/python:3.8` is published.
