### ISSUE TITLE
golang 1.3.3 image

### ISSUE THREAD

**Issue by chenrui333** [circleci/circleci-images#448]
Looks like golang v1.13.2 or v1.13.3 image does not exist yet.

relates to https://github.com/golang/go/releases/tag/go1.13.3

Relates to https://github.com/roboll/helmfile/pull/897

**Comment by felicianotech** [comment]
It takes time. Please see this blog post: https://circleci.com/blog/build-image-update-schedule/

We also have a new image that will eventually replace this one in public beta. It already has both of today's Go releases: https://github.com/CircleCI-Public/cimg-go

**Comment by chenrui333** [comment]
@felicianotech Thanks a lot!
