### ISSUE TITLE
Docker image circleci/android:api-29 needs Java 9

### ISSUE THREAD

**Issue by ldavison** [circleci/circleci-images#458]
The circleci/android:api-29 Docker image uses Java 8. For SDK 29, we need Java 9 to run Robolectric tests, see: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.3.1

Tests currently fail with:

```
java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 29 requires Java 9 (have Java 8)
```

**Comment by felicianotech** [comment]
Hmm. I still need to do more research on this as changes like this can affect many customers.

If we were to bump the OpenJDK version for this image, the next "LTS" (so to speak) for OpenJDK is OpenJDK v11.

Does that sound like something that might work for you?

**Comment by ldavison** [comment]
Thanks for taking a look at this. I understand the concerns for how this might impact other customers. I suspect most Android developers (myself included) set the source/target JDK version though:

```gradle
// build.gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

If that doesn't work, maybe a different tag? eg, `android:api-29-java11`

To confirm, I have been using Java 11 locally since April of this year without issue.

**Comment by ldavison** [comment]
Finally getting back to this. Robolectric deals with this using `circleci/openjdk:9.0.4-12-jdk`, since they also use Circle:

https://github.com/robolectric/robolectric/blob/f18298821c821339693e17b5aa4d5cc42629f72b/.circleci/config.yml

Hopefully this will help others out until this issue can be resolved.

**Comment by yogurtearl** [comment]
@felicianotech JDK 11 images would be appreciated.

maybe under a different tag? `circleci/android-jdk11:api-29`

You will need to switch from the deprecated `SDK tools` package circa 2017 used here: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/2b7c5a72fb826a6735718e79ad7ca66a58023c5e/android/images/api-29/Dockerfile#L166

See deprecation notice:  https://developer.android.com/studio/releases/sdk-tools

and instead use the new Command Line Tools package: https://developer.android.com/studio#cmdline-tools

**Comment by felicianotech** [comment]
Java v11 is scheduled: https://github.com/circleci/circleci-images/issues/494

**Comment by felicianotech** [comment]
Published

**Comment by tinder-inakivillar** [comment]
this is breaking the access of `UseCGroupMemoryLimitForHeap` in images

**Comment by jalonsogarcia** [comment]
It indeed breaks the access of UseCGroupMemoryLimitForHeap, and basically all my builds.

**Comment by job13er** [comment]
RE: `UseCGroupMemoryLimitForHeap`

[This post](https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e) explains about the deprecation of that in Java 10 and how you may want to use the newly available `-XX:+UseContainerSupport` and `-XX:MaxRAMPercentage` instead.

**Comment by hoombar** [comment]
If you have tests running anything to do with formatting currencies, or anything else related to locales, you might also see issues. The locale data changed [in JDK 9](https://www.oracle.com/java/technologies/javase/v9-issues-relnotes.html#JDK-8008577)

for this test
```
    @Test
    fun `format shows correct symbol for mixed locale`() {
        Locale.setDefault(Locale.forLanguageTag("en-IN"))

        val formatted = CurrencyFormatter.format(Currency.getInstance("INR"), 1.0)

        assertThat(formatted).isEqualTo("Rs.1.00")
    }
```

I'm seeing this error on Circle
```
expected: Rs.1.00
but was : ₹ 1.00
```

**Comment by jalonsogarcia** [comment]
Is there any way to use the docker image circleci/android:api-29 with java 8?

**Comment by hoombar** [comment]
I tried reverting to use `circleci/android:api-29`, but it looks like that's also running Java 9

**Comment by hoombar** [comment]
It looks like it's possible to pin images: https://circleci.com/docs/2.0/circleci-images/#using-a-docker-image-id-to-pin-an-image-to-a-fixed-version

I found the last known working docker image for us, and am using that now, which seems to be working.
```
circleci/android@sha256:061e2535826cc3fe4c4a440e716bf06c36c80401ee635c339c6803b3e427ebb3
```

It's only a short term fix, I think in the long term, we'll have to look at updating the version of Java we're building with.

**Comment by jalonsogarcia** [comment]
Thank you! I'll give that a try 👌

**Comment by gyosida** [comment]
I didn't know about this change. Would be nice to inform your users about this. Not everybody is looking into this repo everyday.

I moved from 28 to 29 yesterday and my pipeline broke yelling

`e: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor`

Because of the move from java 8 to 11.

I didn't know where to get the sha for a working version, fortunately I found this commit https://github.com/hadilq/AndroidLifecycleHandler/commit/f406caa264d2e70d8aa00afe6f13ac63ca52c50a and now is up and running. Hope that helps somebody else.

**Comment by danielgomezrico** [comment]
I was using `circleci/android:api-29` for a long time and now they are broken, +1 to have a different image with this java version updated and let the ones working without any touch.

**Comment by danielgomezrico** [comment]
@felicianotech please take a look to this comments ^^

**Comment by felicianotech** [comment]
Hi @danielgomezrico. This change is already complete. You can look at the [Discuss thread](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601/10) that you've already post on for migration information or how to manually stick with an old, unsupported image.
