### ISSUE TITLE
Intentional switch from Node v10 to Node v12?

### ISSUE THREAD

**Issue by danielbachhuber** [circleci/circleci-images#460]
Hi,

I'm using `circleci/php:7.2-node-browsers` which seems to have switched from Node v10 to Node v12 in the last few days.

Was this intentional?

**Comment by felicianotech** [comment]
Yes. This was originally announced 18 days ago [here](https://discuss.circleci.com/t/convenience-image-node-variants-will-be-updated-to-v12-x-on-november-4th/33065?u=felicianotech), and then again a week ago [here](https://discuss.circleci.com/t/docker-convenience-image-updates-november-2019/32752?u=felicianotech).

Please ask questions like this in CircleCI Discuss in the future.

**Comment by felicianotech** [comment]
Also, so there's an "announcements" category of CircleCI Discuss, which is where the two post I posted above are published in. I'd suggest signing up for updates to that category within Discuss. Will be a great way to stay on top of updates like this.

**Comment by danielbachhuber** [comment]
> Yes. This was originally announced 18 days ago [here](https://discuss.circleci.com/t/convenience-image-node-variants-will-be-updated-to-v12-x-on-november-4th/33065?u=felicianotech), and then again a week ago [here](https://discuss.circleci.com/t/docker-convenience-image-updates-november-2019/32752?u=felicianotech).
> 
> Please ask questions like this in CircleCI Discuss in the future.

Sorry, I didn't know to look there.



> Also, so there's an "announcements" category of CircleCI Discuss, which is where the two post I posted above are published in. I'd suggest signing up for updates to that category within Discuss. Will be a great way to stay on top of updates like this.

Just did, thanks!
