### ISSUE TITLE
RabbitMQ image - details?

### ISSUE THREAD

**Issue by glebsts** [circleci/circleci-images#469]
Hello,
I found one of our projects is using `circleci/rabbitmq:3.6.6` image and I am trying to understand how it works and how I can auto-create exchange with minimal effort.
But I found literally zero information. 
`https://hub.docker.com/r/circleci/rabbitmq` has a github link but github has no rabbit mentioned at all. Second link leads to CircleCI documentation which, after using Search, gives only one entry for "RabbitMQ" which is just "The following services can be externalized; <..> RabbitMQ"

What am I doing wrong?

**Comment by felicianotech** [comment]
Hi,

This image you mentioned is for internal use only. It is not for CircleCI users. The link to docs is to show you images that are for public use. CircleCI doesn't offer a RabbitMQ Convenience Image.

You can create one yourself or find one that's publicly available for you to use. While I haven't used it myself, there is a Docker Library image you can look at: https://hub.docker.com/_/rabbitmq
