### ISSUE TITLE
circleci/windows@2.2.0 needs Windows SDK version 8.1

### ISSUE THREAD

**Issue by jamesmcguirepro** [circleci/circleci-images#475]
Please add Windows SDK version 8.1 to the `circleci/windows@2.2.0` image.

It should not conflict with other Windows SDK versions.

Thanks!

**Comment by jamesmcguirepro** [comment]
Here's a link to the Windows 8.1 SDK:
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

It's the first item under "Earlier Releases"

**Comment by felicianotech** [comment]
@jamesmcguirepro I accidently closed this with a PR but this Issue needs to be closed regardless. This repository is for legacy CircleCI Convenience Images. These are Docker/Linux based images. For the Windows machine images, please open a Support ticket.
