### ISSUE TITLE
circleci/windows@2.2.0 importing cert to CurrentUser fails due to ACCESS_DENIED error

### ISSUE THREAD

**Issue by jamesmcguirepro** [circleci/circleci-images#476]
# Background
* We need to import a pfx file (certificate store) to sign one of our projects as part of the build process.
* We use a quick powershell script to do this, in particular the `Import-PfxCertificate` command

This script fails:
```
Import-PfxCertificate -FilePath {pfx_file}-Password {password} -CertStoreLocation cert:\CurrentUser\My
```
with this error:
```Import-PfxCertificate : Access denied. (Exception from HRESULT: 0x80090010)```

While this one works:
```
Import-PfxCertificate -FilePath {pfx_file} -Password {password} -CertStoreLocation cert:\LocalMachine\My
```

**Comment by felicianotech** [comment]
This repository is for legacy CircleCI Convenience Images. These are Docker/Linux based images. For the Windows machine images, please open a Support ticket.
