### ISSUE TITLE
Ruby images not publishing

### ISSUE THREAD

**Issue by nwjsmith** [circleci/circleci-images#477]
👋 Hey there! It looks like the latest versions of the Ruby images are not publishing successfully:

https://app.circleci.com/pipelines/github/circleci/circleci-images/579/workflows/da21ae96-599e-4d16-97fa-9f715801f928/jobs/32057

It looks like the build is failing when building the `ruby:2.6.6` images. This is preventing us from building our own CI images, which inherit from these. Is there anything we can do to help?

**Comment by felicianotech** [comment]
Thanks for reporting. I'm looking into this.

**Comment by felicianotech** [comment]
It is available now. Thanks again.

Also as an FYI, the next-gen version of the Ruby image is currently in public beta. You can learn more about that [here](https://discuss.circleci.com/t/new-ruby-convenience-image-public-beta/33274/2).

**Comment by nwjsmith** [comment]
Awesome, thanks Ricardo!
