### ISSUE TITLE
adroid:api-29 is missing latest build tools

### ISSUE THREAD

**Issue by fargus9** [circleci/circleci-images#481]
Build tools 29.03 is missing from the api-29 image.

**Comment by fargus9** [comment]
I had added it here but realized those files are autogenerated. https://github.com/CircleCI-Public/circleci-dockerfiles/pull/26

**Comment by felicianotech** [comment]
Thanks. Working on it.

**Comment by fargus9** [comment]
I also ran into this issue:

> As I was testing api-29 with a different build-tools version I noticed /opt/android/sdk/build-tools/29.0.2/llvm-rs-cc: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory.

**Comment by felicianotech** [comment]
I'm not sure yet about your latest comment. If that's an issue with the image, please create a new Issue.
