### ISSUE TITLE
Provide circleci/php:7.4-stretch-node

### ISSUE THREAD

**Issue by VincentLanglet** [circleci/circleci-images#482]
Debian stretch is still supported to June 2022.

There is a circleci/php:7.3-stretch-node, but I saw no circleci/php:7.4-stretch-one.

Would it be possible to modify the script in order to build an images with stretch and php7.4 ?

**Comment by felicianotech** [comment]
We cannot. This image is based on the upstream/official Docker Library PHP. They make this kind of decision. You'd need to ask this question over at their official repository: https://github.com/CircleCI-Public/cimg-shared/pull/20

If they were to add Debian Stretch back, then we'd get it within 24-48 hours. I hope that helps.

**Comment by VincentLanglet** [comment]
Thanks @felicianotech I (maybe) be back ! 😅
