### ISSUE TITLE
Android Image Getting Java v11

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#494]
The Android image uses Java v8 right now. Many tools are now not only supporting Java v11 or newer, some are even requiring it. The Java version in the Android image will be updated by August 3rd, 2020.... unless enough people make an argument to move it up to July.

**Comment by maxirosson** [comment]
Any update about this? Are you going to offer a different docker image with java 11 so we can decide when migrate to it?

**Comment by felicianotech** [comment]
Yes. The date has been pushed to August 17th. [I wrote a post on CircleCI Discuss](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601?u=felicianotech) that you can read as well.

Once the change happens, they'll only be Java 11 images though we'll over images for testing soon so you can start testing ahead of time.

**Comment by felicianotech** [comment]
Testing images are now available, please see this [CircleCI Discuss post](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601/2?u=felicianotech). You can report any issues with these images here or on the Discuss post.

**Comment by Allen-HiCharlie** [comment]
Hey Ricardo, for me, it looks like the image is downloading and then failing with `Error: No such image: ccistaging/android:api-27-node`:

```
Allens-MacBook-Pro:CharlieAndroid allen$ circleci local execute
Docker image digest: sha256:ea6c856572603d47e8f5e8013f8a0b45c0fb91267a6a80ff51068a25e97ed6cd
====>> Spin Up Environment
Build-agent version  ()
Docker Engine Version: 19.03.12
Kernel Version: Linux 938c3b96be96 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux
Starting container ccistaging/android:api-27-node
  image cache not found on this host, downloading ccistaging/android:api-27-node
api-27-node: Pulling from ccistaging/android
6ec8c9369e08: Already exists 
3aa4e9b77806: Already exists 
6d8b5d3bc409: Pull complete 
c52c1e05e8da: Pull complete 
0af7eb2221c4: Pull complete 
68d7b64d2e6a: Pull complete 
87feaa7e560a: Pull complete 
305fbd8ea8cd: Pull complete 
bca396ab11bd: Pull complete 
f24d0692e635: Pull complete 
c37fbe12a864: Pull complete 
e718dd0a9045: Pull complete 
ca6920849560: Pull complete 
570c02a2ee01: Pull complete 
d19db89a8c0a: Pull complete 
bbbc267b6786: Pull complete 
596214f14c10: Pull complete 
d0acab459054: Pull complete 
3c3eb0f6373f: Pull complete 
3667802de7a5: Pull complete 
271cdb9f3460: Pull complete 
ef276e8f36b1: Pull complete 
af0369be9f24: Pull complete 
1cc10da25868: Pull complete 
aae83ee46b12: Pull complete 
34d443805852: Downloading [==============================>                    ]  251.1MB/418MB
8da30f868cda: Downloading [===========>                                       ]  233.5MB/987.3MB
fac9c651dca4: Download complete 
5952f364ab5b: Download complete 
5c2c425c36c5: Download complete 
2bae2587c0c0: Download complete 
Error:   error starting container ccistaging/android:api-27-node: Error: No such image: ccistaging/android:api-27-node

Error: 
Error: No such image: ccistaging/android:api-27-node

Step failed
Task failed
Error: Error: No such image: ccistaging/android:api-27-node
```

Here is a simple my config.yaml that repros the issue:
```
version: 2.1
orbs:
  android: circleci/android@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: ccistaging/android:api-27-node

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      # Standard CircleCi Setup
      - checkout
```

Am I missing something here?

**Comment by felicianotech** [comment]
The images have been updated.

**Comment by tinder-inakivillar** [comment]
@felicianotech is giving CircleCi compatibility support for java 8 images in android 29?

**Comment by tmtrademarked** [comment]
Just as a heads up for anyone who finds their way here via the internet - I believe that JDK 11 isn't compatible with Robolectric <= 4.2.1. It looks like newer Robolectric versions may support this since it's mentioned in the release notes for [4.4-beta-1](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.4-beta-1), but I haven't managed to try this for myself.

**Comment by croitor-ivan** [comment]
Hi there, 
after the update to the v11 openJDK 
the following error apeared.

 Task :app:minifyDevReleaseWithR8 FAILED
/usr/local/openjdk-11/lib/rt.jar: R8: File not found: /usr/local/openjdk-11/lib/rt.jar

**Comment by HughIngram** [comment]
@tmtrademarked thanks for pointing that out. My unit tests were flaking after this change, but I upgraded my Robolectric dependency from `4.3.1` to `4.4-beta-1`, and they are passing now.

**Comment by muraziz** [comment]
We are using circleci/android:api-28-ndk-r17b image, but it's still downloading same image before the update and now: `circleci/android@sha256:c59e1323820b731742e0bb0530706cdf118a939ab9baa41fc2471b168d4dd6fa`. Do I have to change config somehow to trigger downloading newest image?

**Comment by mmathieum** [comment]
If anyone has this issue:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```
Replace `$ANDROID_HOME/tools/bin/sdkmanager` with `sdkmanager` in `/.circleci/config.yml`

**Comment by a396901990** [comment]
> If anyone has this issue:
> 
> ```
> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
> 	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	... 5 more
> ```
> 
> Replace `$ANDROID_HOME/tools/bin/sdkmanager` with `sdkmanager` in `/.circleci/config.yml`

@mmathieum i have same problem, could u provider more information, how did u replace $ANDROID_HOME/tools/bin/sdkmanager with sdkmanager

**Comment by danielgomezrico** [comment]
@mmathieum can you explain why that works?

**Comment by mmathieum** [comment]
@danielgomezrico it seems that there are multiple `sdkmanager` installed.
And only the one in the PATH is compatible with Java 11

**Comment by danielgomezrico** [comment]
@mmathieum mm ok, the only solution I found was sticking to the old image like:

```
image: circleci/android@sha256:061e2535826cc3fe4c4a440e716bf06c36c80401ee635c339c6803b3e427ebb3
```

**Comment by akvashi** [comment]
Anyone have a recommended way to get around the issues with missing annotations? Currently the top search refs a GitHub project that is someone's personal project, not exactly a option for "enterprise" projects to depend on. 

Obviously we could just add this class to our project directly but wondering if anyone knows a more standard way to do this. @mmathieum I believe this is similar to the issue you are facing and may have to basically do the same thing but for your missing classes since they have since been removed from the JDK

**Comment by mmathieum** [comment]
I know it's an old closed issue but to really solve the problem, you have to: 
- install the `cmdline-tools;latest` component (currently version 3.0)
- use `$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager`

https://developer.android.com/studio/command-line#tools-sdk

https://developer.android.com/studio/releases/sdk-tools
