### ISSUE TITLE
Unable to make Geckodriver and Firefox work for CircleCI

### ISSUE THREAD

**Issue by bhadmus** [circleci/circleci-images#496]
I have this project that I am running with Python and Behave. It was working fine when I was only using chrome to execute it. But I decided to make it a bit dynamic such that it can run on firefox and chrome browsers. I have edited the **config.yml** and I still got an error. My config.yml looks like this:
```
version: 2



jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
```

    steps:
      - checkout

      - run:
          name: Install requests
          command: |
            sudo pip install -r requirements.txt

      - run:
          name: Install and start geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz &&
            tar -xvzf geckodriver* &&
            chmod +x geckodriver &&
            sudo mv geckodriver /usr/local/bin

      - run:
          name: Install the latest firefox
          command: |
            sudo apt-get remove firefox-mozilla-build binutils &&
            sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list" &&
            sudo apt-get update &&
            sudo apt-get install -t sid firefox &&
            firefox --version

      - run:
          name: Run Selenium test
          command: |
             behave ./Features/guest_shopper.feature --no-capture

      - store_artifacts:
          path: ./screenshots
          destination: screenshots-file
      - store_artifacts:
          path: ./log
          destination: logs-file

And the error, I got on circleCI looks like this:

> 2020-06-11 06:47:17 (9.32 MB/s) - ‘geckodriver-v0.26.0-linux64.tar.gz’ saved [2390549/2390549]
> 
> tar: geckodriver.log: Not found in archive
> tar: Exiting with failure status due to previous errors

Please can someone help me here? what am I doing wrong

**Comment by gmemstr** [comment]
I bet it's the duplicate `tar` calls:

```yaml
        tar -tvf geckodriver* &&
        tar -xvzf geckodriver* &&
```

Would you mind removing the first one and seeing what happens?

**Comment by bhadmus** [comment]
> I bet it's the duplicate `tar` calls:
> 
> ```yaml
>         tar -tvf geckodriver* &&
>         tar -xvzf geckodriver* &&
> ```
> 
> Would you mind removing the first one and seeing what happens?

It isn't. I intentionally put the first one because the first one drops a list of content in the file. I have removed it and it is still the same result.

**Comment by dsayling** [comment]
@bhadmus - I noticed that firefox doesn't start in the image as headless by default (chrome seems to start fine without the options). Assuming you're using selenium inside of behave, you'll need to add the firefox options to the driver on startup.

```
from selenium.webdriver.firefox.options import Options as FOptions
from selenium import webdriver
firefox_options = FOptions()
firefox_options.add_argument("--headless")
with webdriver.Firefox(options=firefox_options) as driver:
    driver.get("http://localhost:8080")
```

**Comment by dsayling** [comment]
@bhadmus - I updated my demo flask app to work with geckodriver version you specified and the python-3.6.2-browser image. See the diff here: https://github.com/dsayling/ssfa/pull/8/ I also had to make sure the `marionette` capability was turned off (this was not necessary at later versions of the tools).

**Comment by bhadmus** [comment]
@dsayling Thank you! this worked for me. I copied some stuff from your `config.yml` file. I also added `DesiredCapabilities`

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FOptions
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

cap = DesiredCapabilities().FIREFOX
cap["marionette"] = False
firefox_options = FOptions()
firefox_options.add_argument("--headless")
driver = webdriver.Firefox(capabilities=cap, options=firefox_options)
```

Though I experience some errors due to flakiness. I can handle that. Thank you very much.
