### ISSUE TITLE
Support Java8 Android29 image

### ISSUE THREAD

**Issue by tinder-inakivillar** [circleci/circleci-images#503]
Today it was updated the base image of Android 29 with Java 11. This causes failing our builds. It's possible to offer an android 29 image with Java8.
We didn't be notified and we need to test our processes with Java11.

**Comment by pawelkw** [comment]
Same issue. All builds suddenly started failing killing all the productivity for the rest of the day. We're unable to merge/release.

**Comment by michaelcarrano** [comment]
Same issue here.

**Comment by felicianotech** [comment]
This change was discussed both [on GitHub](https://github.com/circleci/circleci-images/issues/494) and in [CircleCI Discuss](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601?u=felicianotech) for at least two months. There was also images to test ahead of time for 3 weeks.

For anyone who needs to use an old Java 8 image right now, you can pin your image by using the SHA256 hash. You can learn how to get the hash [here](https://support.circleci.com/hc/en-us/articles/115015742147-Pinning-a-Docker-Image-to-a-Specific-Version).

I'm going to close this Issue. If there's more discussion/troubleshooting questions, please post in the [forum thread](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601?u=felicianotech).

Also, if you get a hash for a specific tag, please share with others on the forum in case someone else might also want that hash.

**Comment by tinder-inakivillar** [comment]
@felicianotech we are customers of circleci paying money for the service. We weren't notified about anything, you post two links of discussion where only you were discussing this topic.
This change implies we need to test our process with java11. 
Please consider next time have more visibility in these changes because we are blocked now and the response can't be I mentioned in one thread.

Can you share the link of the hash?

**Comment by michaelcarrano** [comment]
Still waiting for build to complete but I found this hash on previous build that was passing this morning before the Java 11 change.

`circleci/android@sha256:b6646fdf7457f61825526e7bfce364d8e533da6ceb1cdb98e371e94348ecc834`

Sure this change was communicated but it was not noticeable, I don't check CircleCI Github or the forums often. Only do so when an issue comes up. Could it have been possible to parse the config.yml file and provided a notification for us within CircleCI itself?

**Comment by felicianotech** [comment]
> Sure this change was communicated but it was not noticeable, I don't check CircleCI Github or the forums often. Only do so when an issue comes up. Could it have been possible to parse the config.yml file and provided a notification for us within CircleCI itself?

Point taken. We don't have this ability at the moment but definitely something that we can do to better communicate this. An in-app banner and emails for projects that use an affected image are on my list so far from feedback collected.

**Comment by croitor-ivan** [comment]
Hi there,
after the update to the v11 openJDK
the following error appeared on the builds requiring obfuscation.

Task :app:minifyDevReleaseWithR8 FAILED
/usr/local/openjdk-11/lib/rt.jar: R8: File not found: /usr/local/openjdk-11/lib/rt.jar

**Comment by Blahartinger** [comment]
'Discussion for 2 months'
Fuck you guys.

**Comment by cesards** [comment]
Same here.

**Comment by Blahartinger** [comment]
I'm a paying customer, but please by all means censor my frustrations made in comments. Just don't break my builds without notifying me in any way about multiple major version runtime changes ever again. 
You made Travis look good today, be proud.

**Comment by Xinkle** [comment]
Build was failed due to
```
* What went wrong:
Failed to notify build listener.
> javax/xml/bind/DatatypeConverter
```

I pinned the previous success android image. and it worked.
But eventually, I should to use latest image, how do I fix the issue with new android-29 image?

**Comment by hseung** [comment]
Another build error here

Case 1)
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.8'.
```

Case 2)
```
> Task :app:kaptDebugKotlin FAILED
e: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

I've also fixed the issue by using a pinned the previous image, but I think you guys have to provide us a "stable" docker image with java 8.

**Comment by floschu** [comment]
> This change was discussed both [on GitHub](https://github.com/circleci/circleci-images/issues/494) and in [CircleCI Discuss](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601?u=felicianotech) for at least two months. There was also images to test ahead of time for 3 weeks.

Such a breaking change has to be communicated to (**paying**) customers via a medium that will alert them. An email would have been nice for example. 😬

**Comment by halfhp** [comment]
Frustrating is an understatement.  I'm still in a state of shock and concern that someone thought/thinks this is ok.

**Comment by chrisnoodoe** [comment]
This issue kills me ...
