### ISSUE TITLE
How to add vi/vim/nano or other stuff with sudo apt-get

### ISSUE THREAD

**Issue by ptmkenny** [circleci/circleci-images#505]
I'm using a custom version of the circleci/php:7.4-node-browsers image with some behat tooling.

When I used ssh to check my tests, I was surprised to find that there is no vi/vim/nano text editor available to make changes to code/verify things.

I found this discussion (https://ideas.circleci.com/ideas/CCI-I-920) but no concrete steps about how to add vi/vim.

So I added this line to my Dockerfile:

`RUN sudo apt-get update && sudo apt-get install -y vim`

However, this results in an error:

```
Step 50/50 : RUN sudo apt-get update && sudo apt-get install -y vim
---> Running in 526166a9043b
[91m
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:
#1) Respect the privacy of others.
#2) Think before you type.
#3) With great power comes great responsibility.
[0m
[91msudo: no tty present and no askpass program specified
[0m
Removing intermediate container 526166a9043b
The command '/bin/sh -c sudo apt-get update && sudo apt-get install -y vim' returned a non-zero code: 1
```

What's the correct way to add vi/vim/nano to a CircleCI docker image?

**Comment by gmemstr** [comment]
@ptmkenny You \*should\* be able to drop the `sudo` prefix, since the image is built with the root user by default.

**Comment by ptmkenny** [comment]
Running without `sudo` gave me this error:
```

Step 50/50 : RUN apt-get update && apt-get install -y vim
---> Running in c65e3186a744
Reading package lists...
[91mE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
[0m
Removing intermediate container c65e3186a744
The command '/bin/sh -c apt-get update && apt-get install -y vim' returned a non-zero code: 100
```

**Comment by gmemstr** [comment]
Curious - I assume your Dockerfile looks something like this?

```
FROM circleci/php:7.4-node-browsers

...

RUN apt-get update && apt-get install -y vim
```

I would normally recommend switching to our `cimg` images (https://github.com/CircleCI-Public/cimg-php), but there is no `-browser` variant at the moment.

**Comment by ptmkenny** [comment]
This is the dockerfile: https://github.com/ptmkenny/docker-build-tools-ci/blob/php74behatbrowsers/Dockerfile

This file was provided by my webhost (Pantheon) so it would be very easy to switch to some other image.

**Comment by gmemstr** [comment]
Looks like `vim` is being installed after switching away from the root user- you would probably want to add `vim` to this block:

```
# Install necessary packages for PHP extensions
RUN apt-get update && \
     apt-get install -y \
        dnsutils \
        libmagickwand-dev \
        libzip-dev \
        libsodium-dev \
        libpng-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        zlib1g-dev \
        libicu-dev \
        g++
```

This would ensure you don't have to `apt update` again, and that it uses the root user.

**Comment by felicianotech** [comment]
@ptmkenny Did that help?

**Comment by ptmkenny** [comment]
@gmemstr Thanks, that fixed it!

@felicianotech Sorry for the late response.  Closing this issue now.
