### ISSUE TITLE
Circle CI pipeline ionic android failed after August 17th change

### ISSUE THREAD

**Issue by belizar** [circleci/circleci-images#507]
Hello,
After this specific change
![image](https://user-images.githubusercontent.com/37871475/90668218-1a885b80-e226-11ea-910e-e5b9f336d5da.png)

My CircleCI pipeline is failing.

Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.8
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.
CordovaError: Requirements check failed for JDK 8 ('1.8.*')! Detected version: 11.0.8
Check your ANDROID_SDK_ROOT / JAVA_HOME / PATH environment variables.

I need some solution here please, my team is not able to build an ionic android application

**Comment by felicianotech** [comment]
Please see [this forum thread](https://discuss.circleci.com/t/android-convenience-image-moving-to-java-v11-on-august-17th/36601/4?u=felicianotech) for migration troubleshooting.
