### ISSUE TITLE
Missing libxss1 after circleci/ruby:2.7.1-node-browsers updated on DockerHub

### ISSUE THREAD

**Issue by ro-savage** [circleci/circleci-images#514]
The commit that changed the `circleci/ruby:2.7.1-node-browsers` 
from `DIGEST:sha256:919028ba2abddd4a00228549bfc3d4bc9a0a19d48bb9246be5a8503a4afa9416`
to `DIGEST:sha256:d7946dc5a7e6e91e4afa6667c97e3488574fa4d5a4fc0c0394167bf3405ae71a`

Which was probably https://github.com/CircleCI-Public/circleci-dockerfiles/commit/4dc3c99e17e336b50c99395228e1cb77cd41435c#diff-ef79851f615b7db7da9f5ef96e4f856c (@felicianotech) broke our builds because the image is now missing `libxss1` 

I assume since it was the same change made to dozens of images, this applies to all those images.

`error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory`

**Comment by ro-savage** [comment]
Reverting to the old hash, everything works as before and `libxss1` is correctly installed.

**Comment by kulas115** [comment]
Same problem here. All of a sudden all my builds are failing due to missing dependency.

@ro-savage how have you reverted to old hash to make it work?

**Comment by timocov** [comment]
The same here for `circleci/node:12-browsers`

**Comment by ro-savage** [comment]
For anyone else looking. You can update your image to use the has like

`circleci/ruby:2.7.1-node-browsers`
to
`circleci/ruby@sha256:919028ba2abddd4a00228549bfc3d4bc9a0a19d48bb9246be5a8503a4afa9416`

And we found the has by looking at an older passing CircleCI Build and finding the hash 
![image](https://user-images.githubusercontent.com/9244507/91432544-f972db00-e8b5-11ea-9aa8-49a7b4fe34fe.png)

However, our solution was to use `sudo apt-get install libxss1` encase this was a deliberate breaking change.

**Comment by felicianotech** [comment]
Thanks for reporting. Taking a look.

**Comment by felicianotech** [comment]
This issue appears to be caused by a change with Google Chrome. Google recently released Google Chrome v85 which appears to have dropped `libxss1` as a dependency in the .deb package. Without any other installed package depending on it, `libxss1` simply wasn't installed.

I'm working on a fix to manually install this package again in the `-browsers` variant.

**Comment by felicianotech** [comment]
A fix has been made. The change is rolling out to all active images now. Please allow up to 45 minutes for the image to update.

**Comment by danielnaab** [comment]
I see that `circleci/ruby:2.6.6-node-browsers-legacy` was updated, but we're still getting this bug with the latest version of that tag. Upgrading to `circleci/ruby:2.7-node-browsers-legacy` worked.

**Comment by felicianotech** [comment]
@danielnaab You're using the legacy browsers variant which doesn't get updates. Can you try using the supported browsers variant and let me know how that works?

**Comment by danielnaab** [comment]
> @danielnaab You're using the legacy browsers variant which doesn't get updates. Can you try using the supported browsers variant and let me know how that works?

Sure, I can give that a shot Monday. I'm confused, though - both the images I've tried were working as of a few days ago, and were last updated 19 hours ago:

https://hub.docker.com/layers/circleci/ruby/2.6.6-node-browsers-legacy/images/sha256-97abdc1258438209d927cb2a65da2c6803b8bd6db3710da73c912dbdf1ca113c?context=explore
https://hub.docker.com/layers/circleci/ruby/2.7-node-browsers-legacy/images/sha256-21482bcd35e6b93c18ab910a9b2c4ec51c2b836526e1ed6349313a01484b4d0d?context=explore
