### ISSUE TITLE
api-24-node JDK 8 version docker file

### ISSUE THREAD

**Issue by rajendrarama** [circleci/circleci-images#516]
I am trying to find the Dockerfile for circleci/android:api-24-node JDK 8 version. Unable to find anywhere.

**Comment by felicianotech** [comment]
The repository that contains Dockerfiles for legacy Convenience Images is linked in the readme of this repo.

Specifically for what you asked, the last Dockerfile for that tag can be found here: 
https://github.com/CircleCI-Public/circleci-dockerfiles/blob/0ab09295b0ef966b3bcefcae8f9d9c82e8f19404/android/images/api-24-node/Dockerfile

I hope that helps.
