### ISSUE TITLE
Request for a Ruby 2.7.1 Debian Stretch image

### ISSUE THREAD

**Issue by cmdoptesc** [circleci/circleci-images#518]
Hi Folks,

I updated my Ruby from 2.6.6 to 2.7.1 and changed the CircleCI image. However, the Buster image raises some GCC errors when I was building Cap’n Proto:

```
g++: error: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o: No such file or directory
g++: error: /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o: No such file or directory
g++: error: /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o: No such file or directory
g++: error: /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o: No such file or directory
make: *** [Makefile:1915: libkj.la] Error 1
```

Is it possible for someone to build a convenience image for Ruby 2.7.1 in Debian Stretch? Right now, it's only offered in Buster [here](https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/ruby/images):

Thanks you,
al

**Comment by felicianotech** [comment]
Hi Al,

Looks like there's a LDD path problem? I looked for two of those files and both are available in either image as they are provided in the `libc6-dev` package:

```
~/Sandbox $ docker run -it circleci/ruby:2.7.1 dpkg -S crti.o
                      libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/crti.o
~/Sandbox $ docker run -it circleci/ruby:2.6.6 dpkg -S crti.o
                      libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/crti.o
~/Sandbox $ docker run -it circleci/ruby:2.6.6 dpkg -S crtn.o
                      libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/crtn.o
~/Sandbox $ docker run -it circleci/ruby:2.7.1 dpkg -S crtn.o
                      libc6-dev:amd64: /usr/lib/x86_64-linux-gnu/crtn.o
```

The legacy Convenience Images (the images under the `circleci/*` namespace) are built on top of upstream Docker Library images. So the decision on which base OSs that are available are determined by them and our images just inherit it. You can make a request over at the [upstream GitHub repository](https://github.com/docker-library/ruby) for Stretch images though I'm not sure if they'll want to reintroduce an older OS.

For the next-gen Convenience Images, we have a new Ruby image (`cimg/ruby`) that is Ubuntu-based. While the newest Ruby images would be Ubuntu 20.04 based, the `2.6.6` and `2.7.1` tags are both Ubuntu 18.04 based. Maybe that would help?
