### ISSUE TITLE
/usr/local/bin/composer is not accessible from PHP images

### ISSUE THREAD

**Issue by wundo** [circleci/circleci-images#52]
Tested with circleci/php:7.1.4-cli-browsers

**Comment by zzak** [comment]
Hello @wundo,

Are you sure it's not available from here?
https://github.com/circleci/circleci-images/blob/30939b17ee05423bb6bf49dbded86e1ae2a38f57/php/generate-images#L9-L14

It looks like we installed it in the right place, what do you think? I'm not familiar with PHP toolchain.

**Comment by wundo** [comment]
@zzak I runned this image with SSH in circle, and the wasn't a composer in /usr/local/bin/

As I don't have access to the actually generated Dockerfile it's kind of hard for me to debug this.

**Comment by wundo** [comment]
@zzak any news?

**Comment by felicianotech** [comment]
This was fixed sometime in the past few months.

Newer versions of the Docker PHP 7.1.x, 7.0.x, and 5.x images properly include Composer.
Testing a few out myself, the 7.1.9 has it and the 7.0.22 and newer have it.
