### ISSUE TITLE
Issues with capybara and recent ruby-2.7.2-node-browsers images

### ISSUE THREAD

**Issue by colszowka** [circleci/circleci-images#526]
Hey all,

first of all thanks for providing these very handy images!

Not sure this is really actionable but we have run into problems using the `circleci/ruby:2.7.2-node-browsers` image recently and I figured at least I should write this up somewhere so other people investigating this problem maybe will find their way here and contribute their input too instead of walking through the fog like I did :foggy: 

### The situation

We are using the `circleci/ruby:2.7.2-node-browsers` for CI builds of a smallish internal rails app.

The stack (all versions up to date):

* rails
* rspec
* selenium-webdrivers and webdrivers gems
* capybara using `selenium_chrome_headless` driver for browser-based feature specs

### The problem

Starting around two weeks ago our CI build started failing in an estimated 75% of cases. with the following error as soon as they reached some specs utilizing chrome:

```
Failure/Error: visit "/"
            Selenium::WebDriver::Error::InvalidSessionIdError:
              invalid session id
            # #0 0x55af6ca83d99 <unknown>
```

The specs were running fine on our development environments all the time, so we started investigating whether this was due to a change we introduced via `git bisect`, but ultimately we realized that this was not the case, we were getting the same kind of exceptions for commits from early october which went through CI successfully at the time, but not now, the underlying image being the only difference.

Ultimately we tried things against an older, explicit image ID of `circleci/ruby:2.7.2-node-browsers` from a successful earlier CI build's logs. We used `circleci/ruby@sha256:af3af73dd24a2f3e5c8b0e40236c2a865ebcfc431a39d0452f5098558db2d140` which shoulld be from late October, and we do not run into this issue there.

I tried to make a little reproduction sample app using `rack` and `capybara`, but could not reproduce the issue there unfortunately. However, I'm pretty sure based on my findings that sometime in early november something changed within the `circleci/ruby:2.7.2-node-browsers` images published that causes issues. In `htop` when the test suite is running when the problem occurs I can see chrome start and immediately stop again. Maybe something changed to chrome itself, or the underlying packages used to build it have changed?

Feel free to close this issue as likely this is not really actionable, but maybe having this written up and findable via Google will be helpful to others already.

**Comment by colszowka** [comment]
Just another note, I ran https://github.com/GoogleContainerTools/container-diff against the known-to-be-working, FWIW for apt packages it lists only chrome as being different

```
$ container-diff diff circleci/ruby@sha256:af3af73dd24a2f3e5c8b0e40236c2a865ebcfc431a39d0452f5098558db2d140 circleci/ruby:2.7.2-node-browsers --type=apt

-----Apt-----

Packages found only in circleci/ruby@sha256:af3af73dd24a2f3e5c8b0e40236c2a865ebcfc431a39d0452f5098558db2d140: None

Packages found only in circleci/ruby:2.7.2-node-browsers: None

Version differences:
PACKAGE                      IMAGE1 (circleci/ruby@sha256:af3af73dd24a2f3e5c8b0e40236c2a865ebcfc431a39d0452f5098558db2d140)        IMAGE2 (circleci/ruby:2.7.2-node-browsers)
-google-chrome-stable        86.0.4240.111-1, 228M                                                                                 86.0.4240.198-1, 228.1M
```

**Comment by colszowka** [comment]
*sigh* Nevermind me, the issue just appeared on the old image as well, so it must be something else. I will close this as apparently it isn't related to the docker image itself after all, sorry for the noise!

**Comment by felicianotech** [comment]
@colszowka No worries, thanks for following up.
