### ISSUE TITLE
Clojure Docker Image cannot run AWS SAM CLI 

### ISSUE THREAD

**Issue by TheSuri** [circleci/circleci-images#528]
Is it possible to update the clojure docker image to also have Python 3.7 packaged with it so that we can install the AWS SAM CLI orb - which only supports python 3.7 and python 3.8?

**Comment by ryanwohara** [comment]
You can use an orb to easily install Python 3.7 or 3.8 within your project. We will not force Python on all our convenience images because only a small subset of the uses require it.
