### ISSUE TITLE
golang:1.16beta1 has not propagated to circleci images

### ISSUE THREAD

**Issue by leighmcculloch** [circleci/circleci-images#531]
Hi, The Go 1.16 Beta 1 released was made on December 27th 2020 and the official Golang docker images received that release under the `1.16beta1` tag but that tag has not become available in the CircleCI images.

I expected to see an image `circleci/golang:1.16beta1` exist within 24 hours after the upstream `golang:1.16beta1` posted, but it has not appeared.

https://hub.docker.com/_/golang?tab=tags&page=1&ordering=last_updated&name=1.16beta

I am hoping to use Go 1.16 beta1 CircleCI image here in https://github.com/stellar/go/pull/3288.

**Comment by felicianotech** [comment]
Hi. CircleCI doesn't publish non-stable releases by default for Convenience Images. The next versions to publish for Go will be patch releases for v1.14.x or v1.15.x or the official v1.16 release when it comes out next month.

**Comment by leighmcculloch** [comment]
>CircleCI doesn't publish non-stable releases

CircleCI publishes Go release-candidates, which are non-stable releases of Go. For example: [1.15rc2](https://hub.docker.com/r/circleci/golang/tags?page=1&ordering=last_updated&name=1.15rc2).

Supporting beta and release candidate builds are critical for testing Go applications. Some folks in the Go community participate in testing beta and release candidates.

Would it be possible to at least continue to publish release-candidate builds, and would it be possible to consider also publishing beta builds?

**Comment by felicianotech** [comment]
Good point. Those RC images happen to have gotten through, they're not intended nor supported.

As for this image, `circleci/go`, if RCs are already getting through, that would continue to work. I would like to point out though that this image is replaced by the next-gen Go image, `cimg/go`. You can learn more [here](https://circleci.com/developer/images/image/cimg/go).

Next-gen images doesn't support RC and beta images yet but it is something I'm looking to try and support officially for 2021. You can stay informed on Go images changes [here](https://github.com/CircleCI-Public/cimg-go) and [here](https://discuss.circleci.com/c/ecosystem/circleci-images).

Lastly, I created a [CircleCI Idea](https://ideas.circleci.com/images/p/support-beta-and-rc-versions) that you can upvote and track this feature request. You can find that [here](https://ideas.circleci.com/images/p/support-beta-and-rc-versions).
