### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [circleci/circleci-images#537]
Hi team,

I am trying to use **circleci/node** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I have tried to build the image using the command **docker build -t <image_name > .** on arm64 platforms but is failing for arm64.

I made some changes in order to resolve the errors and have successfully built the image on my local arm64 machine.

**Commit link:** https://github.com/odidev/circleci-dockerfiles/commit/d7ee3e047fdd093cc748641643074bd6623cb65f

Do you have any plans on releasing arm64 images?

It will be very helpful if the image is released with ARM64 support. If interested I can work on it and raise a PR.

**Comment by felicianotech** [comment]
Hi,

CircleCI Convenience Images do not support any ARM platform nor are there any immediate plans to do so. There is a [CircleCI Ideas](https://ideas.circleci.com/images/p/support-for-arm-based-docker-images) feature request you can track and upvote if you are interested.
