### ISSUE TITLE
go1.16.4

### ISSUE THREAD

**Issue by magiconair** [circleci/circleci-images#547]
Hi, go1.16.4 has been out for 2 weeks. When can we expect a circleci/golang:1.16.4 image?

![image](https://user-images.githubusercontent.com/229005/119093581-2b156e80-ba10-11eb-810a-83a101cb3824.png)

**Comment by magiconair** [comment]
Can work around this by using the go orb.

**Comment by BytesGuy** [comment]
@magiconair Hello 👋 This version is available in our next-gen Go image: https://circleci.com/developer/images/image/cimg/go
