### ISSUE TITLE
Dockerfile Repo Read-Only?

### ISSUE THREAD

**Issue by BeeeQueue** [circleci/circleci-images#548]
The dockerfile repo seems to have been set to read-only, meaning it stopped getting updated two months ago?

We don't have any images for new versions like `node:14.17`, `node:16.x`

**Comment by BeeeQueue** [comment]
Saw the post about convenience images now.

**Comment by KyleTryon** [comment]
For anyone who may stumble across this, our current images can always be found here: https://circleci.com/developer/images
