### ISSUE TITLE
Android Images - No need for multiple SDK images

### ISSUE THREAD

**Issue by StefMa** [circleci/circleci-images#56]
Hey ⚫️ci guys 🙋‍♂️,

currently I'm experience a little bit with Bitbucket Pipelines (sry for the advertising 🙃) and docker as well.

I found out that the `sdkmanager` can install the missing but required SDK tools packages automatically. 
> When you run a build from the command line, Gradle can automatically download missing SDK packages that a project depends on, as long as the corresponding SDK license agreements have already been accepted using the SDK Manager.

See here in the [official docu](https://developer.android.com/studio/intro/update.html#download-with-gradle).

Which means that you don't need to provide so many docker images for different Android API levels.
The only thing you have to do is to set the correct SDK path to the `local.properties` file in the Android project you are running.
This can be archived with [this little line](https://github.com/uber-common/android-build-environment/blob/master/Dockerfile#L128) of code.

All in all: 
I think [that code](https://github.com/circleci/circleci-images/blob/master/android/Dockerfile.m4#L45-L51) can be removed and you only need one docker image for android 🙃

**Comment by gildor** [comment]
I think that current approach is better for CI than automatic on-demand downloading.
Because now SDK for particular API level is part of docker image, if it will be part of build process user also should configure caching just to avoid particular platform downloading.

**Comment by ryanwohara** [comment]
You're welcome to build your own images. We want quick Android images ready-to-go for CI. The time saved from 1.0 to 2.0 using these images is often 20+ minutes or 75+%.
