### ISSUE TITLE
Mariadb circle ci image is failing with message "Build was canceled"

### ISSUE THREAD

**Issue by kavyaimversion** [circleci/circleci-images#571]
<img width="1121" alt="Screenshot 2022-04-21 at 5 45 01 PM" src="https://user-images.githubusercontent.com/55223491/164455944-6fd574fa-2364-40ff-8eee-7847ac10219c.png">

**Comment by ryanwohara** [comment]
These images have been deprecated.

**Comment by felicianotech** [comment]
Hi,

These images have been deprecated and thus no longer supported. Please use `cimg/mariadb` instead of `circleci/mariadb`. If you still have an issue or further questions, please report them here: https://github.com/CircleCI-Public/cimg-mariadb

Respectfully,
Ricardo N Feliciano
