### ISSUE TITLE
Android image with Android build tools 31 installed

### ISSUE THREAD

**Issue by satranj2000** [circleci/circleci-images#572]
I am looking for Android image which has Android Build tools 31 installed. 

If I check this link ( https://circleci.com/developer/machine/image/android  ) and use the image ( android:2021.12.1 ) , the build tool version is 32 ( in the folder - /opt/android/sdk/build-tools/32.0.0 )
 
If I use the earlier image ( android:2021.10.1 ), it says the build tool version as 30.0.2

**Comment by satranj2000** [comment]
Thank you. Please ignore this query. I ran the sdkmanager and installed the build tools as a separate step using the existing Android image. 

sdkmanager --install "build-tools;31.0.0"

**Comment by felicianotech** [comment]
Glad you were able to figure it out. In case anyone else comes across this, yes this is the recommended way to install a specific version of an Android tool if that version isn't pre-installed in an image.
