### ISSUE TITLE
Adding a react-native image

### ISSUE THREAD

**Issue by mihirk** [circleci/circleci-images#67]
Would you be willing to accept a PR adding a react-native docker image?

**Comment by DanToml** [comment]
@mihirk I'd definitely be interested in seeing this! - Potentially as a variant of the `android` image?

**Comment by mihirk** [comment]
@dantoml it would be a combination of a node and android image with react-native-cli pre installed.

**Comment by mihirk** [comment]
@DanToml How do you propose going about this? 
The major issue I see is the permutation and combinations of versioning between android, node and react-native-cli. 

Suppose I use Android 25, Node 8.5 with RNCli 2.0.
The tag would look something like 25-0.8.5-2.0. 

There is also another issue, most react project would be using Android Libraries whose compile android version is different from their project versions, which might require 2+ versions of android sdks and buildtools to be present in the image. 


Proposition:
The react-native image should have all versions of Android installed, and the node and react-native cli version should be the tag.

**Comment by kpachar** [comment]
@mihirk If possible could you please add a license to your OpenCHS/react-native-image repository so that I can reuse it until there is an official circleci image for this?
Thanks

**Comment by mihirk** [comment]
@kpachar Done - https://github.com/OpenCHS/react-native-image/blob/master/LICENSE
