### ISSUE TITLE
Android NDK images

### ISSUE THREAD

**Issue by gildor** [circleci/circleci-images#73]
Current images for Android support only Android SDK. So you cannot build project with NDK.

I don't think that NDK should be a part of SDK image, just because NDK is very big and has own versions.

I suggest adding additional set of images for NDK builds: 
`android:api-${API_LEVEL}-ndk-${NDK_VERSION}`

Of course, NDK has many version and we don't want to get combinatorial explosion for images, but probably the support of the latest version of NDK is good enough.

I would happy to contribute.

**Comment by marcomorain** [comment]
Good idea @gildor - I'd love a PR for this.

I think you are correct, the latest NDK should be all we need.

**Comment by levlaz** [comment]
Sorry didn't see this before opening https://github.com/circleci/circleci-images/issues/138 -- will close that issue out and work on a PR for this. :)

**Comment by iynere** [comment]
this should be resolved once this workflow finishes ! https://circleci.com/workflow-run/cefa061e-92eb-40de-ba1b-f18f93e83c1e see #241
