### ISSUE TITLE
Handle installing custom versions of Yarn more easily

### ISSUE THREAD

**Issue by felicianotech** [circleci/circleci-images#76]
For Node images, if the user would like to install their own version of Yarn, the pre-installed version takes precedence in PATH.

Two options off the top of my head:

- install Yarn in a way that it simply gets overridden by the default install instructions from their website
- install Yarn in a way that it's location in `PATH` is lower priority

This Issue is picking up where Yarn's left off: https://github.com/yarnpkg/yarn/issues/4407

**Comment by mikemaccana** [comment]
I'd be all for an apt based install for Debian and rpms for Red Hat, as that's what yarn's install uses. 

 - It'll be there for customers by default
 - It won't conflict for customers who upgrade

PS. looks like even after I remove the binary, globals are still being installed to the old unpackaged global dir (and hence `mocha` won't run from the command line after `yarn install global mocha` ). Is there a way I can stop this?

**Comment by felicianotech** [comment]
I'm pretty sure all of these images are currently based off of Debian Jessie so .deb makes sense.

**Comment by felicianotech** [comment]
So the plot thickens. It looks like we don't actually involve ourselves in touching Yarn at all in these images. Most of our images are based off the Docker Library images and the official Node.JS image already includes Yarn.

So the result of this is two things:

1. CircleCI doesn't manage the Yarn install. If you would like to change how it's installed, you'd have to do it upstream for the official Node.JS Docker image.
1. Upstream updated the version of Yarn in the official Node.JS image only 3 hours ago. You can see the commit [here](https://github.com/nodejs/docker-node/commit/2924f142789842282890f7b1736578b49b3be78f). Our images can take up to 48 hours to update from upstream as noted in [our blog post](https://circleci.com/blog/official-image-maintenance/).

So I'd say within 48 hours from right now, our images will have Yarn v1.0.1, which is what upstream just switched to.

Just in case you want to go check it out, here's one of their recent Dockerfiles built about 30 minutes ago. As @Daniel15 mentioned in the Yarn Issue that spurred this, they are installing Yarn via the tarball which is causing your issue: https://github.com/nodejs/docker-node/blob/2924f142789842282890f7b1736578b49b3be78f/8.5/Dockerfile#L53

**Comment by mikemaccana** [comment]
Thanks @felicianotech going to try to get the image fixed.
