### ISSUE TITLE
Error during startup of postgres:9.6-postgis image

### ISSUE THREAD

**Issue by merwok** [circleci/circleci-images#84]
I was advised by email of the availability of postgres images tailor-made for CircleCI, so I switched from mdillon/postgis to circleci/postgres:9.6-postgis.  This error happened:

```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/postgis.sh

Exited with code 3CREATE DATABASE
UPDATE 1
Loading PostGIS extensions into template_postgis
ERROR:  could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis;
ERROR:  could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
LOG:  received SIGHUP, reloading configuration files
LOG:  parameter "listen_addresses" cannot be changed without restarting the server
LOG:  configuration file "/var/lib/postgresql/data/postgresql.conf" contains errors; unaffected changes were applied
```

**Comment by ryanwohara** [comment]
Thanks for opening this issue. I am actively looking into a solution.

In the meantime, the `alpine` variation will work as expected.

**Comment by ryanwohara** [comment]
Thanks for your patience while we get them tested & published!

https://github.com/circleci/circleci-images/pull/85/files

**Comment by merwok** [comment]
Great news!  I realized I used the postgis variant out of habit, but my current project doesn’t actually need it so I switched to your alpine variant which works.  I’ll test with the classic 9.6 and later with postgis on a different project.  Thanks!
