### ISSUE TITLE
Please include Firefox 56+ in the browsers image

### ISSUE THREAD

**Issue by joemccall86** [circleci/circleci-images#86]
This fixes certain issues we face with more modern versions of selenium, and would also allow us to run in "headless" mode.

**Comment by jonathanong** [comment]
not sure where my issue went, but they tried to add it but it didn't work, so they had to revert it.

**Comment by jonathanong** [comment]
i'd rather give my money to circle than sauce labs ;)

**Comment by ryanwohara** [comment]
We will ultimately move to headless Chrome and a newer Firefox at about the same time. We still need (for now) to support older testing suites that don't play well with Firefox 56.

**Comment by yuki24** [comment]
I figured this out and am using the following to replace the pre-isntalled firefox with the latest firefox:

```yaml
- run:
    name: Install and start geckodriver
    command: |
      wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz &&
      tar -xvzf geckodriver* &&
      chmod +x geckodriver &&
      sudo mv geckodriver /usr/local/bin

- run:
    name: Install the latest firefox
    command: |
      sudo apt-get remove firefox-mozilla-build &&
      sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list" &&
      sudo apt-get update &&
      sudo apt-get install -t sid firefox &&
      firefox --version
```

**Comment by jeromemacias** [comment]
Thanks @yuki24, I needed to add `sudo apt-get remove binutils` just before install into your second command and it works

**Comment by noce2** [comment]
thanks @jeromemacias  you helped with some errors I was seeing when i ran @yuki24 's instructions.

**Comment by cherewaty** [comment]
This won't get you all the way to Firefox 56+, but it at least got us to 52 without relying on a `sid`/unstable distribution:
```
      - run:
          name: Install the latest Firefox ESR
          command: |
            sudo apt-get remove firefox-mozilla-build &&
            sudo apt install firefox-esr &&
            firefox --version
```

**Comment by ryanwohara** [comment]
https://github.com/circleci/circleci-images/pull/237

itshappening.gif
