### ISSUE TITLE
Go 1.9.2 and Go 1.8.5

### ISSUE THREAD

**Issue by nathany** [circleci/circleci-images#94]
Released on October 25th

https://groups.google.com/forum/#!topic/golang-announce/s_hLxKF9ApA

When I specify golang:1.8.5 in my circle.yml, I see this message:

```
Build-agent version 0.0.4275-16f7565 (2017-09-26T14:09:58+0000)
Downloading previous test results
Starting container circleci/golang:1.8.5
  image cache not found on this host, downloading circleci/golang:1.8.5
Error response from daemon: manifest for circleci/golang:1.8.5 not found
```

(CircleCI Enterprise)

The older version of Go is working fine for now.

**Comment by nathany** [comment]
There appear to be some other 1.8.5 images, but not just a straight 1.8.5 as there is with 1.8.4. Likewise for 1.9.2.
https://hub.docker.com/r/circleci/golang/tags/

**Comment by felicianotech** [comment]
Hmm, I wanted to assume it was because of upstream but they appear to have the standalone tags. https://hub.docker.com/r/library/golang/tags/

Looking into this.

**Comment by felicianotech** [comment]
I'm not sure what the issue was but these tags are available on Docker Hub now.

**Comment by oshalygin** [comment]
`circleci/golang:1.9.2 not found`

Getting this right now, anyone have any clue whats going on?

**Comment by felicianotech** [comment]
@oshalygin This is a different, closed issue. Please follow this instead: https://github.com/circleci/circleci-images/issues/214
