### ISSUE TITLE
Node 9.0 issue

### ISSUE THREAD

**Issue by vipulnsward** [circleci/circleci-images#95]
circleci/ruby:2.4.2-node-browsers seems to have picked up node 9.0.

But this new version is not compatible yet for many major projects: https://github.com/sass/node-sass/issues/2129

Any way we can either downgrade or specify our own version?

**Comment by vipulnsward** [comment]
Using a custom script for now. But its probably good idea to pin down the version on official images, since things are broken for mostly everyone right now.

**Comment by renchap** [comment]
Maybe it would be a good idea to use Node LTS in these kind of images? Node 8.9.0 is the new LTS and the one recommended for production use and I think it would fit better on all images where Node is a "secondary" package.

**Comment by felicianotech** [comment]
I agree. This should be pinned to LTS releases. Will get this updated.

**Comment by felicianotech** [comment]
@vipulnsward This issue has been fixed. We're now pinning NodeJS variants to the latest LTS release (currently, v8.9.0).

Thank you for reporting this. Much appreciated.

**Comment by vipulnsward** [comment]
Thanks!
