### ISSUE TITLE
Bundler version pinning

### ISSUE THREAD

**Issue by vipulnsward** [circleci/circleci-images#98]
Current ruby-2-4-node-browsers image picks up latest bundler 1.16.0.
But since it has an issue with --path : https://github.com/bundler/bundler/issues/6144
caching is currently of not much use and using path, basically fails all bundler commands as it is not able to load and gems.

Can we pin it down to lower release 1.15.4? Or allow a way to configure it.

**Comment by zzak** [comment]
@vipulnsward Thank you for the heads up, on 1.0 we were [pinning to 1.14.x](https://github.com/circleci/circleci-images/issues/98) to avoid these kinds of issues that seem to always pop up when they cut a release.

I'd be more than happy to do the same in our 2.0 images.

**Comment by vipulnsward** [comment]
I guess https://github.com/docker-library/ruby/commit/8a4631f3750e594f394e4bda97d71999d9439179

is what caused this?

**Comment by eric-hu** [comment]
Yep, it looks like it.  I opened an issue upstream in the docker-library/ruby repo [here](https://github.com/docker-library/ruby/issues/171).  It looks like they automate upgrading bundler, but they pointed us in the direction of a way to cherry-pick their image before it gets to their bundle upgrade.  We're discussing how to best approach this internally as well, to balance current stability for CircleCI customers with long term maintenance (we trust the official Docker images to generally represent community needs better than we could do on our own).

For the moment, we've [posted](https://discuss.circleci.com/t/ruby-2-4-2-failing-after-latest-update/17855/8?u=eric) how to work around this by using Bundler 1.15.4.

**Comment by zzak** [comment]
Tested here: https://circleci.com/gh/CircleCI-Public/circleci-demo-ruby-rails/36
